import React from "react";
import '../../css/dt.css';
import ReactPlayer from "react-player";
import img1 from '../../../img/News/American_Trio_Blazes/1.webp';
import img2 from '../../../img/News/American_Trio_Blazes/2.webp';
import img3 from '../../../img/News/American_Trio_Blazes/3.webp';
import img4 from '../../../img/News/American_Trio_Blazes/4.webp';
import img5 from '../../../img/News/American_Trio_Blazes/5.webp';
import img6 from '../../../img/News/American_Trio_Blazes/6.webp';
import img7 from '../../../img/News/American_Trio_Blazes/7.webp';
import img8 from '../../../img/News/American_Trio_Blazes/8.webp';
import img9 from '../../../img/News/American_Trio_Blazes/9.webp';

const American_Trio_Blazes =()=>{
    return(
        <div className="test">
            <h1>American Trio Blazes Spectacular New Route up 9000-foot North Face of Jannu</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>With 'Round Trip Ticket' (M7 AI5+ A0), Alan Rousseau, Jackson Marvell, and Matt Cornell have established one of the most impressive Himalayan routes in recent memory.</p>
            <img className="img_bv" src={img1}></img>
            <p>American alpinists <a href="https://www.instagram.com/jackson_marvell/">Jackson Marvell</a>, <a href="https://www.instagram.com/rousseaualan/">Alan Rousseau</a>, and <a href="https://www.instagram.com/matt_cornell25/">Matt Cornell</a> were huddled together in their tiny alpine shelter—all wrapped up in a three-man sleeping bag—when a rock ripped through the fly like a sniper round.</p>
            <p>The trio was perched above 23,000 feet on the North Face of Jannu (7,710m/25,295ft), in the Kanchenjunga Himal of far eastern Nepal. They were three days into a new route, camped on an exposed fin of snow. Their tent was hanging part way off the side of their snow platform, and rockfall had peppered their tent all night. “I slept with my arm around Alan, who was in the middle, all night long, just trying to keep myself on the platform,” Marvell recalled.</p>
            <p>Now they were looking at an eight-inch gash in the tent. “We used two locking carabiners to stitch it up,” Marvell said. “They acted kind of like fabric clamps,” Rousseau added, chuckling. “Honestly, we were amazed it worked.”</p>
            <p>Tent-ripping rockfall was far from their only snafu. The trio’s shelter was buried in the bergschrund on approach by constant spindrift. They were pounded by rockfall and falling ice constantly, pushed off the face by 15 mph winds, and struck by a collapsing snow mushroom high on the headwall, not to mention pushing through thousands of feet of extremely technical, nails-hard vertical climbing at dizzying altitudes. When Climbing spoke with Rousseau and Marvell, both were in a hospital in Kathmandu recovering from frostbite, but remained in high spirits.</p>
            <img className="img_bv" src={img2}></img>
            <p>Jannu, also known as Kumbhakarna, has been a longtime objective for all three. Marvell and Rousseau made a strong attempt in 2021, reaching 23,600 feet, as did Rousseau and Cornell in 2022. In 2023 the trio was finally all together, and with help from an $8,000 AAC Cutting Edge Grant, they were knee-deep in what would become the proudest send of any of their careers. “Everything came together. We had the energy of our whole team, and perfect weather to do this thing,” Marvell said.</p>
            <p>Also known as the “Wall of Shadows,” the North Face of Jannu, a sheer rampart soaring almost to the peak’s summit, has witnessed some of the most technical high-altitude climbing in history. The face was first partially climbed in 1976, by a Japanese team who angled off the face to the east ridge to avoid the final, steep headwall. 1989 saw a direct (claimed) ascent by controversial Slovenian soloist Tomo Česen, though most regard this as bunk, along with several of his other more outrageous claimed feats.</p>
            <img className="img_bv" src={img3}></img>
            <p style={{fontStyle:'italic', textAlign:'center'}}>Alan Rousseau on the glacial plateau beneath Jannu’s immense North Face. The team climbed a long 5.8 rock rib and vertical seracs to get to this point. (Photo: Matt Cornell)</p>
            <p>The first verified <a href="https://publications.americanalpineclub.org/articles/12200505600/The-North-Face-of-Jannu">direct ascent of the North Face </a> came in 2004, with a heavy aid effort by a Russian team under Alexander Odintsov. The group won a Piolets d’Or for their efforts but ignited some controversy for leaving a large amount of gear behind on the wall, as well as the “siege-style” manner of their ascent (55 days, 10 climbers, an overwhelming amount of fixed ropes, and so on).</p>
            <h2>High, Hard Climbing</h2>
            <p>Rousseau, Cornell, and Marvell had an altogether different style in mind. The team traveled light and fast, carrying a small G7 alpine shelter and two inflatable portaledge pods, bundling together in a custom-built three-person sleeping bag. “This was our first time tripling up [in a single sleeping bag],” Rousseau said. “It was awesome.”</p>
            <p>On October 7 they set off from a camp at 15,400 feet, crossing a rock glacier and climbing a rock buttress at around 5.8. “Above that, we got into an icefall, climbing through vertical seracs, making our way up onto this hanging glacier plateau,” said Rousseau. The team slept in the North Face’s bergschrund at 19,000 feet that night at the base of the steep, upper mountain.</p>
            <img className="img_bv" src={img4}></img>
            <p>During the night, heavy spindrift piled up around their shelter. “We got pretty pounded,” Marvell said. “It was piling up slowly, so we weren’t at risk of getting buried, but it was seriously stacking up, collapsing our tent a bit, so we had to get out and excavate in the middle of the night.”</p>
            <p>In the morning, they climbed a “snice” (snow/ice) ramp feature on the wall, traveling from 19,000 feet to almost 22,000 feet. The first 1,000 feet of snice was nearly vertical, though protected well with a bit of effort, and they bivied beneath a steep rock buttress.</p>
            <p>The third day saw them up to 23,300 feet. “That was where the technical climbing really begins,” Rousseau said. “Above [22,000 feet]. From that point on it was M5/AI5—climbing that you have to pay attention to—to get established up in the headwall.”</p>
            <p>This night was the night they carabiner-stitched their tent fly, and in the morning of the fourth day the technical climbing began in earnest. Above them was all new terrain, higher than any high point they’d reached in the two prior seasons. They led the route in blocks, with each member typically tackling three to four 150-foot pitches at a time.</p>
            <img className="img_bv" src={img5}></img>
            <p style={{fontStyle:'italic', textAlign:'center'}}>Marvell leads a steep pitch (note the tag line hanging in space) low on the headwall, at 7,200 meters (23,600ft). (Photo: Matt Cornell)</p>
            <p>Though the trio covered barely 500 feet that first day on the headwall, things went smoothly. “It was really nice, we had a great window,” Marvell said. “The weather kept on opening, and we didn’t have a big rush to move fast in that terrain. We were all climbing our pitches well.” Difficulties reached up to M7/AI5, but never stymied the team.</p>
            <p>While Cornell followed a pitch, Marvell and Rousseau were hit at the belay by a large snow mushroom that collapsed from a roof high above them. The collapse, which totally buried Marvell and Rousseau, luckily missed Cornell, though he could no longer see his companions at all, enveloped in the snow. “The force of it was pretty great,” Marvell said, “and there were a lot of chunks in it, but it didn’t feel like it would’ve knocked you off the face.” That night—the team’s first hanging bivy—they set up in the yawning cavity where that snow had fallen from.</p>
            <p>“Day five was more of the same,” said Rousseau. “We started right off the bat with gnarly hard climbing on a vertical panel. Matt led a pretty impressive block sustained in the M7 zone that eventually got us up to where we slept at [24,600 feet] in another hanging belay.”</p>
            <img className="img_bv" src={img6}></img>
            <p style={{fontStyle:'italic', textAlign:'center'}}>Rousseau belays Cornell as he leads out from a tension traverse to link sheets of ice at ~7,300m (24,000ft) on day five. (Photo: Jackson Marvell)</p>
            <p>They’d budgeted 2,500 calories per day, but by this point, their calorie consumption had dwindled to a mere 800 to 1,000. “By the time we got high, we were really losing appetite,” Marvell said. “I wasn’t able to put down bars during the day.” This wasn’t just an appetite issue. Their bars and gels also kept freezing, as did their water, despite insulated bottles. “On that vertical of a face, it’s really challenging to stop, get out a stove, and brew,” Marvell said. As a result, by the time they were high on the wall, he was eating only one dehydrated meal at the end of the day, and perhaps a bar in the morning.</p>
            <p>As anyone who has slept (or tried to sleep) at elevation can imagine, the nights grew progressively worse. “Morale was always high, but man, as we got higher, shit went down pretty rapidly,” Marvell said. Luckily the route protected quite well, and though they were incredibly sleep-deprived, the trio recalled no pitches warranting an R or X rating. “There were a lot of crystal pockets on the face,” Marvell said, “so even if you were run out occasionally, you could just look around and find a pocket.”</p>
            <p>That fifth night, in particular, the group was severely fatigued. Rousseau remarked to Marvell, “I remember saying to you guys, ‘I know we have a long way to go, but I kind of feel like we just did something insane.’ And you guys sort of just nodded silently at me. Like, ‘Yeah dude… We’re with you, but we have a long fuckin’ way to go.’ That moment really sticks out for me,” Rousseau said, laughing. “Like, we all should be so psyched right now, but we were destroyed, just hoping to survive at that point.”</p>
            <p>The following day, their last on the route, was “deceptively hard,” said Rousseau. “We kind of wrapped around to the south side of the mountain after topping out the headwall on our side, and we thought it’d be more moderate, but it was still pretty real vertical climbing up until just a couple hundred feet shy of the summit.”</p>
            <img className="img_bv" src={img7}></img>
            <p>On the night of the sixth day, October 12, the team rapped down from the summit, sleeping at their last bivy at 24,600 feet. By the end of the seventh day, they were back at their base camp. </p>
            <h2>Like Cogs in the Machine</h2>
            <p>The team christened their route—entailing nearly 9,000 feet of climbing and a “metric shit-ton” of pitches—Round Trip Ticket (M7 AI5+ A0). Ultimately they used a hint of aid in the form of tension traverses, but predominantly free climbed. It’s certainly the most inspired effort on Jannu to date, if not one of the most impressive Himalayan feats in recent history, and the high point of these alpinists’ careers. </p>
            <p>That’s saying something because Marvell, Cornell, and Rousseau are no slouches. Earlier this year, the trio put up a proud <a href="https://www.climbing.com/news/first-ascent-alpine-climb-mt-dickey-alaska/">FA on Alaska’s Mount Dickey</a> (9,545ft) with Aim for the Bushes (M6 X AI6; 5,250ft), and last year made a <a href="https://www.climbing.com/news/speed-ascent-slovak-direct-denali/?scope=anon">lauded 22-hour speed ascent</a> of the notorious Slovak Direct (5.9 X M6+ WI6 A2; 9,000ft) on Denali (20,310ft). </p>
            <p>But those missions pale in comparison to Round Trip Ticket, they said. “This is definitely a couple of steps beyond anything any of us have done before,” said Rousseau, “[because of] the elevation, the fact that it’s a dead North Face with no sun, and just the days of sustained climbing at that altitude. We always thought of the North Face of Jannu as being the ultimate prize in this style of climbing. And it lived up to those expectations.” “It probably surpassed them,” added Marvell. “Yeah…” Rousseau agreed. “It was fuckin’ awesome.”</p>
            <img className="img_bv" src={img8}></img>
            <p>Teamwork was an integral part of their success on Jannu. All three agreed that the three-man group was crucial to their success, not just from a morale perspective but logistically as well. “Less hard leads per person, less overall weight to carry, it makes it all easier,” said Rousseau.</p>
            <p>There was no conscious decision for any one member to specialize in any section or style of climbing, though in the past the trio has used such an approach. “This time it was just an organic thing,” said Rousseau. “We knew everybody could do everything, so in the morning, it was like, ‘Yo, who wants to tie in?’” </p>
            <p>Climbing difficult vertical ice and mixed pitches is one thing, of course, but when you take that performance and set the stage at 22,000 to 25,000 feet, what once was an impressive athletic endeavor becomes just as much a battle of the psyche. </p>
            <p>“Everything starts to feel more desperate,” said Rousseau. “You have a really small margin. You can’t allow yourself to panic because you don’t have the reserves. You have to focus on efficiency. Control is the ultimate concern. Conservation of energy. We all just started feeling like cogs in the machine. We did our work, and pitch by pitch, it whittled away. Before we knew it, we were on top of the most intimidating feature we could think of.”</p>
            <p>Each member of the climb felt this “cog in the machine” experience. Every man had his own way of describing it, but they all evinced the same almost spiritual experience on the wall. Cornell wrote on his Instagram, “Consumed by events of the climb, we lost the meaning of individuality.” In Rousseau’s words, “The key was surrendering to a super deep flow state that we all entered together.”</p>
            <p>“What was crazy for me is that when I was leading my block, I felt fully engaged,” added Marvell. “You’re functioning at your highest capacity, and you have the team’s trust behind you. And when you’re following, it’s reversed. It’s almost like you can rest because all of your trust is in the leader.”</p>
            <p>(Perhaps sleeping in the same sleeping bag helped them enter this flow state of ultimate trust, though that remains speculation.)</p>
            <h2>Buying a Round Trip Ticket</h2>
            <p>The group named their line after a comment made by Russian Sergey Kofanov in a <a href="https://alpinist.com/features/2007-open/">2007 Alpinist feature.</a> Kofanov and partner Valery Babanov had made an ascent of a new route on Jannu via the West Pillar (“Magic Pillar”) earlier that year. </p>
            <p>In that piece, Kofanov remarks on the allure of the North Face. “I couldn’t tear my gaze away from [it],” he writes. “Its immensity was so mesmerizing it made me dizzy. Such a cosmic cold issued from its frozen granite walls, even when I had my back to it, I felt as if it were watching me. Perhaps someday, a pair will climb a direct route on the North Face in alpine style, but they’ll need to accept the likelihood that they’re buying themselves a one-way ticket.”</p>
            <img className="img_bv" src={img9}></img>
            <p>The men all noted that they dealt with some negativity from friends and loved ones during their years venturing to Jannu. The concerns may have been well-intentioned, but in reality, manifested as toxicity. “I dealt with a lot of unfortunate interactions the first couple of years I went over there,” Rousseau said, “people telling me or my wife that I wasn’t going to come back from this. So this route name was a bit of a ‘fuck you’ to those people. We came here collectively three times, and we bought three round-trip flights. We were intent on coming back every time.”</p>
            <p>“There’s so much talk in the alpine climbing world that if you want to climb hard, you have to accept death as a consequence,” Rousseau continued. “I think that’s true to some extent, but it’s overplayed. The over-emphasis on mortality in alpinism sets us back a bit.”</p>
            <p>All adventure athletes have to find a balance between acceptable and unacceptable risk to practice their sport. If one errs too heavily on the side of caution, they’ll never leave home in the first place. Too far to the other side, and they won’t come back at all. Naturally, everyone draws their line at a different spot. </p>
            <p>The Rousseau-Marvel-Cornell team believes that a big factor in their success is that all three draw their lines in nearly the same spot. They’re willing to accept a comparable amount of risk, and they analyze it in a similar way. For Marvell, the trick lies in staying rational. “If you let your brain tell you that it’s all bad, then that will be your experience. In 2021, we turned around pretty high on the wall because we didn’t have the window we wanted. It was disappointing, but that’s just what you do. So it never felt crazy, like we were climbing into a death trap.”</p>
            <p>“This is the third year we’ve come to this thing,” Rousseau added. “We’ve become pretty strict observers of where things are falling, where avalanches are happening, and how long it takes for the route to clean. We analyze things as in-depth as we can before we launch. We pick the best window, the best forecast, and make no compromise. But once we step into it, we just climb.” </p>
            <p>There are moments, of course, where the team had to come together and reanalyze, such as when the large snow release hit Marvell and Rousseau at their belay. “But once we meet and we make our call, we don’t let ourselves doubt it,” Rousseau said. “Unless the conditions change again—which you have to be open to accepting—then, man, you focus on climbing and nothing else.”</p>
            <p>“Don’t put yourself in that doubting headspace. Just go.”</p>
        </div>

    )
}
export default American_Trio_Blazes;