import React from "react";
import '../../css/dt.css';
import ReactPlayer from "react-player";
import img1 from '../../../img/News/Jesse_Grupper/1.webp';
import img2 from '../../../img/News/Jesse_Grupper/2.webp';
import img3 from '../../../img/News/Jesse_Grupper/3.webp';
import img4 from '../../../img/News/Jesse_Grupper/4.webp';

const Jesse_Grupper =()=>{
    return(
        <div className="test">
            <h1>Grupper had a breakout season on the World Cup circuit, nearly taking the overall lead title; but he’s still unsure about how his climbing helps humanity</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>Grupper had a breakout season on the World Cup circuit, nearly taking the overall lead title; but he’s still unsure about how his climbing helps humanity</p>
            <img className="img_bv" src={img1}></img>
            <p>When I interviewed Jesse Grupper back in November 2021, he had recently flashed Livin’ Astro, a bouldery and complex 5.14c in Rumney, NH, and was just days away from his second consecutive Lead victory at U.S. Nationals—and yet in our conversation, I was surprised to learn that Grupper, though clearly one of America’s most talented sport climbers, was openly ambivalent about his commitment to hard climbing. On the one hand, he cared deeply about the sport and wanted to honor the 14 years of effort he’d put into it; but on the other hand, he was working full time in biodesign lab in Boston (he helped design a hand-rehabilitation exoskeleton for post-stroke patients: essentially gloves that allow patients to replicate therapy sessions at home) and struggling with questions about “how much good [climbing is] doing for others versus just for myself.”</p>
            <p>Since then, much has changed for Grupper. In March he made the U.S. team in both Bouldering in Lead and, after some deliberation, decided “to give one last wack at the whole competitive climbing thing.” He went part-time at the lab and moved to Salt Lake City. Though he struggled mightily at the start of bouldering season (he was one of several competitors unable to get off the ground on any of the problems at Meiringen, his first comp, which he describes as “ the most embarrassing round of competition I’ve ever had”), he turned things around and nearly made semis at the end of the season. In Lead, Grupper’s specialty, he podiumed in the year’s first comp, took gold in two more events, and—despite a series of mishaps—came agonizingly close to winning the overall Lead season.</p>
            <p>So I decided to catch up with Grupper to chat about the year. We talked about his robotics work and about what it was like training with the U.S. team; we talked about the combination of hard work and mental tricks that allowed him to come back from his experience at Meiringen; we talked about the differences between his bouldering and lead training; and we talked about how his health condition—he was diagnosed with ulcerative colitis in during his freshman year of college—impacts both his climbing and his personal understanding of the role that technology can play in improving people’s lives.  </p>
            <img className="img_bv" src={img2}></img>
            <p>THE INTERVIEW</p>
            <p>Climbing: When we talked almost exactly a year ago, I was quite interested in the balance that you were trying to strike between climbing and “contributing to humanity.” This year that balance has included full-time international competitions. I was just wondering how life has changed and what went into that change?</p>
            <p>Grupper: It’s been such a whirlwind of events. The craziest thing for me is that, when we spoke last year, I felt like I had already accomplished a lot in climbing, and it had taken me 14 years to get to that point. It’s crazy to reflect how during the 15th year things can change so much. When we last talked, I was very close to just continuing to do local comps, doing national comps, but potentially never doing the World Cup circuit again… I don’t know… Reflecting on life, it’s incredible how if you have a passion, you have to really just continue to beat it down and go after it in order to see the full fruits of that effort. I would never have thought that the dream of winning a World Cup could come true.</p>
            <p>But, yeah, I went to team trials in March, found out that I was on the team, and then the next month I decided that I would like to give one last wack at the whole competitive climbing thing. I left the lab in May, though I continued working part time for them while competing. It definitely doesn’t feel as hands on as it used to; I’m not working directly with people every day to make their life unequivocally better; but I still think it will help people. Also, it’s been nice to be able to focus on something besides competitive climbing. Having some kind of balance is really useful for keeping my head together in competitions; if a comp doesn’t go well, I still feel like I’m a well-rounded person.</p>
            <p>Climbing:  What did that transition from full-time lab employee to a full-time member of the U.S. team look and feel like?</p>
            <p>Grupper: I think the biggest thing is that I went from training by myself, with my headphones in, to training with people who are better than me and are working as hard as me and are striving for the same thing—and that’s been incredibly motivating. </p>
            <p>Also having the opportunity to train full-time, or mostly full-time, allows me to work on my climbing in ways that I didn’t feel like I fully could before. That’s not to say that someone who has a full-time job can’t do some of these things just as well, but I’m very volume-focused in my training, especially for roped climbing, and I think having time for double sessions—time to really beat the body down, in a good way—is important. Likewise on the recovery side: being able to do daily yoga for longer periods of time, doing daily meditation, foam rolling—that’s all important. </p>
            <p>Climbing:  When you’re on Team USA, you’re climbing with some of the greatest rock athletes that our country has ever produced. I imagine that this comes with a lot of motivation, as you said—but I would be pretty afraid to enter that setting.</p>
            <p>Grupper: Oh, all the fears are there, for sure. But I think the beauty of it is that because we were all going to the same hotels and dinners and breakfasts, I think that you really begin to see people as people and not just as the crazy beasts that they seem to be in the gym. Being able to connect in that way is, for me, really meaningful. They can read your body language a little bit better, read your thoughts a bit more, and be able to support you in the ways that you need support. The beginning of the season was hard for me because it takes time for people to come together, and Bouldering season comes before the Lead season—so I already felt behind. I had just finished work, and hadn’t been training full-time, and I definitely wasn’t as strong as any of the other guys on the Bouldering team at that moment, so I just kept thinking, “Oh, do I really belong here?” At first I was intimidated to try some of the boulders that they were putting up, but over time I built that confidence and felt more invited to try, and I think that my progression in the season had a lot to do with being able to “play with the big boys.” I’ll definitely be conscious of that for new team members.</p>
            <p>Climbing: What was your headspace after Meiringen? Did you need to do some self talk?</p>
            <p>Grupper: I think I’m always quick to be critical of myself, which I think can be an innate talent but is also harmful. After Meiringen, I definitely had some reflection time. There was a two-week gap before the next World Cup, and I decided not to do that one and focus on training. During that next month I tried to find more confidence and also replicate some of the climbs that I’d seen in Meiringen. </p>
            <p>Because I fully underestimated what a Bouldering World Cup would feel like. I think I expected it to be similar to U.S. Nationals, where you may have some climbs that are nails but other climbs that are easier to get off the start. But the truth was that everything felt like nails. Meiringen is notorious for having the hardest, most powerful boulders—which I didn’t know until after, of course—so being able to replicate those moves and do them in training was where I started to build more confidence. </p>
            <p>And there was a perspective change: At the start of the season I was like, “Oh maybe I can make semis,” and then after Meiringen I was like, “I’m just trying to get off the ground next time, that would be awesome,” but then, it’s funny, by the end of the season I was like, “Oh maybe I can make semis after all.” </p>
            <p>Climbing: How do you work on that comp style bouldering? I feel like I could rip my shoulders off at all times. </p>
            <p>Grupper: That feeling doesn’t go away. You’re always gonna feel like you’re ripping your shoulders off. At least for me. But I think that’s a great question. In talking to others on the team—and I’m not necessarily the expert at this yet—but in talking to the others, the biggest problem for me is that, for Lead, I’m always fighting super hard to stay on the wall at all times—because you have only one chance, and that’s all that matters. That means I’m tight, I’m gripped, I’m in a mindset of “I’m not falling here.” Yet when I’m approaching a boulder, I’m still really tight, and I’m not willing to get out of this this box that I often climb in. It’s weird because you’re still fighting in bouldering, but it’s a different kind of fight, where you’re loose enough to almost let go while you’re swinging on the wall. And for me, as a lead climber, letting go while I’m on the wall is just an oxymoron. </p>
            <p>We always talk about Natalia [Grossman] having “dangle arms,” which we mean in a great way. Being able to maximize that swing with straight arms is really important. So in a weird way I think one of the biggest gains I could make in bouldering would be to let go of the fear of falling.</p>
            <p>Climbing: Hmm. I’ll have to think more about that.</p>
            <p>Grupper:  Me too. We’ll think about it together.</p>
            <p>Climbing: Did you have any techniques to help you see the progress that you were making rather than focusing entirely on the negatives, the things that weren’t going as well?</p>
            <p>Grupper: Yeah. I guess I’ll break this into training and competitions. It’s easy to train when you’re “on one”—or whatever the kids are calling it these days—when you’re sending projects or making progress on climbs that previously felt pretty challenging. But the feeling of accomplishment in my workouts is really important for my self-esteem, so I make that be part of the definition of success. I just try to focus on being able to complete the workout that I set out to do. Say someone is trying to do 4x4s. It’s not about sending every climb in that 4×4. It’s just about getting through the workout. When I feel shitty in a gym, I get to interpret that: I might feel bad, I might be falling all over the place, I might be climbing worse than I was a month ago, but if I can still get through the workout, then I can still feel positively towards myself. Instead of being like, “Okay, I’m climbing badly, I’m just gonna quit,” if you’re able to define success before you get on the wall, it makes it a lot easier to accept what you do while you’re at the gym. </p>
            <p>On the competition side, in Bouldering, I’d say that I didn’t know what success looked or felt like; the rounds were so hard sometimes but easier other times, so a top in one competition isn’t the same as a top in another. I think I had to start comparing myself a little bit to others, which isn’t always healthy, but I’ll be honest, I was like, “Okay, not everyone topped this boulder, and you were one of the people who did, so that’s pretty cool. You wouldn’t have been able to do that in the first competition.” </p>
            <p>I think that there’s a healthy way of comparing yourself to others and maybe a less healthy way. There’s definitely a balance. … I would say I mostly used comparison in the positive sense.</p>
            <img className="img_bv" src={img3}></img>
            <p>Climbing: What’s your Lead training like?</p>
            <p>Grupper: A lot of my training comes down to making circuits that are too hard for me. And even if I don’t do it, I’ll still try it up to like 10 times in a day—and that will be one of my sessions. If I fall, I’ll rest for 20 or 30 seconds, then get right back on and keep going with limited rest. So I guess it is high volume with high intensity in some senses. Also, stuff like that was the best way for me to stay physically in shape when I was working full time.</p>
            <p>Climbing: How many moves are your circuits?</p>
            <p>Grupper: I’ll usually set one that’s like 30 moves, and then another that’s like 45. The 30 will have slightly harder moves. The idea is that if you set something that’s harder than you’re going to see in a competition, you’ll feel ready, no matter what.</p>
            <p>Climbing: Have you been able to work any outdoor climbing in? And is that something you still have goals in?</p>
            <p>Grupper: That’s been pretty challenging. In June and July, I had a World Cup almost every weekend. But in late July and August there was more time, so I went to Ceuse for a few weeks—I mainly worked on Bibliography and got very beat up on it, but also made some decent links and progress.When I trained in Innsbruck in August, trying to get outside once a week was really motivating. As much as I can vary what I do in a gym, I think that outdoor climbing is the bread and butter of what being a good well-rounded climber means. I love it. And it’s a good mental escape, a pressure release from competitions. I can be like, well if this comp doesn’t go that great, at least the training that I’m putting in right now can help me outside.</p>
            <img className="img_bv" src={img4}></img>
            <p>Climbing: In our last conversation, you talked about your stepping stones on the way to flashing Livin’ Astro—about how like once you defined flashing Livin’ Astro as a goal, you defined all these sub goals, and those sub goals helped minimize the pressure on the big goal as you started achieving them. Each hard flash like Living in Fear (5.13d) and Simply Redlined (5.14a) and Prince Fatty (5.14b) decreased the pressure on the bigger goal because you’re like, “Well, even if I fail on that, I’ve succeeded in all these other things that I’m really proud of.” So I was wondering: is there an analog to that progression in the indoor comp season?</p>
            <p>Grupper: Yeah, I think one of the biggest ones for me was in the Lead season where, in the back of my head, I hoped to win the overall. And of course, you’re not going to do that with just one competition. It takes a lot of competitions. So a sub goal of that was “Can I podium in a world cup?” And next was “Can I win a World Cup?” </p>
            <p>As it turned out, I had a decent number of hiccups along the way [to the overall]—flagging past the boundary [which caused disqualification] and getting sick at Jakarta. </p>
            <p>Climbing: Oh, I didn’t realize you’d gotten sick.</p>
            <p>Grupper: Yeah, the day before the competition I had a 102 degree fever and then I went to qualifiers and did well enough to make semis. But I was still sick the next day; during semis, immediately after we previewed the climb, I vomited. But in the end, I was just one move away from getting the overall—if I’d just made it one move further in semis, while being sick, I would have taken the title. So it was definitely a hard ending. But that does happen, you know. You can’t succeed at everything you want to do. The nice thing is that that goal doesn’t necessarily go away or have to go away. And along the way I made that first World Cup podium, and I was able to win a World Cup—and that’s still stuff that I’m super proud of, super happy to achieve.</p>
            <p>Climbing: I read in an IFSC interview that you’ve dealt with ulcerative colitis for a while—can I ask you about that? </p>
            <p>Grupper: Yeah, sure. Actually, I was hoping to bring it up if you didn’t ask.</p>
            <p>Climbing: I think there’s this tendency on the part of the lay observer to assume that the people who are performing at the highest level of a sport are super polished perfect versions of humans—that they’ve never actually had to deal with any health problems, which is demonstrably untrue if you look around, but, yeah, maybe you could just talk about your experiences?</p>
            <p>Grupper: Yeah. It’s been a crazy journey. I was bedridden in the hospital for a week two Decembers ago, not sure what my next steps would be, whether I’d ever be able to climb at a high level competitively ever again. So it’s been really cool to have gone from having that image in my mind to where I am now.</p>
            <p>Climbing: Has it gotten worse over time?</p>
            <p>Grupper: The remedies that used to work well have worked less well at times. Before my hospitalization, I was taking an oral medication that sort of suppressed the symptoms. Now I’ve moved into having infusions done on a bi-monthly basis, which has been working fairly well, but it’s only been two years and this is a lifetime disease… so I hope it doesn’t get worse. I can still get flare-ups when the symptoms are especially bad. Luckily I haven’t had a really bad flare-up since being hospitalized, but I used to get them every three months or so, especially around finals and other stressful events. So it kind of makes sense that competitions are not the easiest of times for me; they’re definitely stressful.</p>
            <p>Climbing: So it does affect your climbing?</p>
            <p>Grupper: I still have greater frequency in the bathroom. Especially during competitions. And that probably isn’t something that will go away. I’ve tried to remedy it with meditation and yoga, but I think it’s gonna be a constant challenge. I’ve also had a lot of dietary changes; I’m working with a nutritionist. There are things I’m learning to be proactive about, but it can definitely affect me on competition day or while climbing. When I was first diagnosed, I had this experience at the Red River Gorge, where there was a climb I really wanted to do, and I was nervous about getting on it. I had to go to the bathroom before climbing the route. Then I got on the route and, halfway through, realized, “I need to take and lower right now because I need to go to the bathroom again.” So I definitely have been frustrated by it, but I think my coping mechanisms have improved</p>
            <p>But I don’t know. It’s part of the fun in some way. We’re all given what we’re given, and it’s about how you use it, and how you are able to push through with what you have. It’s part of the puzzle of climbing for me now. This is the disease I’ve had to work through, and it’s not that I’m fortunate to have it, but obviously there are ones where it’s not possible to work through in the same way. I mean, if I was born 20 years earlier, I wouldn’t have had the same opportunity to receive this kind of medication. That’s one reason I’m excited to be in the field of rehabilitation robotics and biodesign in general. Technology can allow people to do what they want to do. And it’s inspiring to me to be able to give back in that way.</p>

        </div>

    )
}
export default Jesse_Grupper;