import React from "react";
import '../../css/dt.css';
import ReactPlayer from "react-player";
import img1 from '../../../img/News/Kai_Lightner/1.webp';
import img2 from '../../../img/News/Kai_Lightner/2.jpg';

const Kai_Lightner =()=>{
    return(
        <div className="test">
            <h1>Kai Lightner Just Did His Hardest Route in Eight Years</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>“If little me could see me now and look at the body, he would probably be like, ‘There's no way he’s climbing that hard.’”</p>
            <img className="img_bv" src={img1}></img>
            <p>He was no kid from Boulder, that much was certain. Essentially the one Black climber in a sea of white, it was hard not to notice him. As he grew, he became bigger and taller and thicker than everyone else. Kai Lightner went on to succeed not because of what he had seen around him, but in spite of what he didn’t.</p>
            <p>After walking into the climbing gym for the first time at age 6, it must have been one tremendous, improbable, and desperate whirlwind. From winning his first Youth National Championship four years later, to winning his first Open National Championship at age 15, to, over the ensuing years, medalling in Youth World Championships in a whopping five times and, of course, signing major sponsorship deals along the way, Kai Lightner became a household name. He’d go on to start his own non-profit, Climbing For Change. He’d be featured in a Milk commercial. He’d continue, despite ongoing efforts, to be a rarity in sport that still needs a lot of work before words like accessible or diverse will apply.</p>
            <p>If you’ve been following Lightner’s career for years, as have I, you’d know that his success came with a cost. “To be honest, I don’t think I ever really mentally recovered from everything, not until after college and after taking time off from the sport,” he’d tell me. </p>
            <p>When Lightner sent Era Vella in 2015, at the time considered 5.14d (although the consensus later fell to 5.14c), it was a first of the grade for him, and not at all surprising. “To me, it didn’t feel like a huge build up to a massive goal, but rather a natural progression in my climbing and my career in general,” he said. “Ok cool,” he remembers thinking, “On to the next!” But six weeks later his mom got sick. Physicians told Kai that if hadn’t brought her to the hospital when he did, she would have likely died in the night. For a time, there was no training or climbing, just his mom—just recovery. The season kicked off without him. He had another major growth spurt. He returned to climbing and had the worst season of his career. </p>
            <img className="img_bv" src={img2}></img>
            <p>“When your confidence is shaken, and then that low confidence is reaffirmed in results, that just reaffirmed all the negative thoughts in my head about myself, about my achievements in climbing,” he says. “It just made me feel like it was the end of the road for me and that maybe I was just too tall for the sport. There were just too many things converging at once. It was very overwhelming.”</p>
            <p>Lightner, of course, was not finished. He’d go on to win several more Championships, including the Open Lead National Championships in 2017 and the Pan-American Championships for lead in 2018. But he wouldn’t send another 5.14c until 2020, and as the years spun by, he continually questioned how hard he, now a full-grown man, could possibly climb. </p>
            <p>But on November 21 this year, just days before Thanksgiving, and after just a few weeks of effort, he sent Joe Kinder’s Life of Villains (5.14d) in the Hurricave, Utah. Climbing caught up with Lightner to ask him about the send, his climbing goals, and how he feels about the future. The interview has been edited for length and clarity.</p>
            <h2>The Interview</h2>
            <p>Climbing: How did your life change after graduating in May 2022?</p>
            <p>Lightner: Since graduating, I took a really keen interest in consolidating the work of my nonprofit. When I first started Climbing for Change at the start of the pandemic, I was a sophomore in college and I was still training and climbing and doing all the other things that being a professional athlete involves. And so a lot of it was really difficult to balance. Luckily, I had a really solid team of people helping me through the growing pains of starting a business. But when the school part was alleviated, I was able to take on a lot more responsibilities in my business and get a handle on things, creating a routine that felt sustainable for me. Once I felt that routine getting along, then I started to ask myself what I wanted my career to look like. Because when big life changes like that come around, you have to reflect on what’s next. For me, the answer was things like Climbing for Change. But I also asked myself whether climbing at a high level should be part of my next step. Did I want to put myself back in that space and potentially risk as much as I had before? Eventually, my answer was no. I realized that if I’m going to do this, I have to do it on my own terms in a way that’s sustainable and healthy. I had to accept that if I couldn’t achieve the levels and heights of climbing that I wanted to without being able to do it in a mindset that was healthy for my body, then I simply just had to give it up, because it wouldn’t be worth it. But by the fall of this year, I felt like I had built myself up enough physically enough. I felt in a good enough mental place to where I wanted to start setting goals and working towards them.</p>
            <p>Climbing: When did you decide to try Life of Villains?</p>
            <p>Lightner: I had the climb in my mind in September or late August. Three years ago, I took a trip to the Hurricave and, on my last day of climbing, tried the route to see if it was possible for me. I thought that it was really hard, but it was within my realm of possibility. From that day, the climb just stayed in the back of my head. And so three years later, when I thought about the next route I wanted to do, Life of Villains felt perfect. It felt right up my alley in terms of style, in terms of the way it climbed. And also, as my career has gone, it seems that I tend to gravitate towards climbs FA’d by Joe Kinder. I’ve done a few climbs by him, including Southern Smoke (5.14c) at the Red. So I was convinced it would be a good project. I came up with a training program, and I reserved the month of September and October just for training. I took my first trip out there at the end of October, and I spent a week there. I realized within that week that sending the climb was possible. Then I left for a week for some work required for Climbing for Change, and then returned to the climb. But then… weather. The temperature spiked 10 or 15 degrees. It was mid-70s all of a sudden, it was raining most of the week, and the humidity was 90%. Plus I kept breaking holds. A lot of the time, I use micro-beta, or holds that nobody else uses because I’m a bit taller than everybody else. So I was breaking off little things. And it just became this frustrating process. But I kept thinking that I just needed one good day. Finally, at the end of the trip, that good day came, and I was able to go to the chains.</p>
            <p>Climbing: How did you feel when you clipped the chains?</p>
            <p>Lightner: I felt relieved. I was happy, but also it was the sense of knowing that I was good enough for this, and that this is something that I can sustainably achieve. But I also thought about little me. If little me could see me now and look at the body, he would probably be like, “There’s no way he’s climbing that hard.” So to be able to train and get to this level and be comfortable in the body that I’m in, I just felt a very holistic sense of satisfaction.</p>
            <p>Climbing: I’m curious how the process of Life of Villains compared with that of Era Vella? </p>
            <p>Lightner: When I was working on Era Vella, I felt a lot of pressure to send it. I felt like it had to get done, otherwise it would be a failure on my end. Whereas this time around, I just felt a very large sense of peace. I was very happy and accepting of just going with the flow of the process and knowing that whatever happens, whether I sent it or not, that’s no testament to where I am in my climbing or who I am as a person. I think that calmer mindset really helped me flow through processes. I don’t think I ever had a day where I felt like I was regressing physically or mentally. Towards the end, I was getting a little frustrated, obviously, but not to the point where I felt like I wasn’t good enough to send the climb. That positive mindset is definitely something I hope to carry with me to future projects as well.</p>
            <p>Climbing: Stepping back to 15-year-old Kai, how did your eating disorder factor into you how you felt about your climbing as you hit those growth spurts?</p>
            <p>Lightner: I think it was more of a mental than a physical recovery. Obviously I needed better eating habits and everything, but the harder part was convincing myself that as I was growing, and as natural changes were occurring in my body, those changes were not actively working against me and I just needed to let them occur. I needed to convince myself that I would become stronger if I just waited it out and pushed to the other side of those changes. Because as long as I was fighting the changes of my body, I was going to stay in that same mental state. And I was never going to accept the fact that, you know, puberty is a good thing—that the body develops because it’s progressing towards something better. That was just something that I couldn’t accept for a long time.</p>
            <p>Climbing: It seems like since becoming a professional athlete, you’ve been slowly learning how to deal with being both a climber and an athlete who has quite a few obligations. How do you feel about managing that balance?</p>
            <p>Lightner: I feel like as of late, especially in the last few years, my mindset has shifted about what matters to me in terms of pushing the sport. I found, especially after college, that climbing hard routes isn’t the end-all be-all. If anything, it’s more fulfilling and important to me to push the sport from a horizontal perspective, expanding who feels like climbing is for them and who it’s accessible for. So whether it’s through my nonprofit work, or is through simply being who I am and what I represent in the sport as a minority at the top, I feel like I’ve been able to open the door for a lot of people who come from backgrounds like mine and who look like me. And I can help them feel like climbing is a space that is inviting. I do feel like I can do both—climb hard and expand the sport horizontally, but I just need to figure out how, and what that balance looks like. I think I’m finally getting the hang of it now.</p>
            <p>Climbing: If you had to name one thing, what is it that has helped you achieve that positive mental space which has allowed you to push yourself back into harder grades?</p>
            <p>Lightner: What’s given me the sense of peace is really knowing that climbing should be fun. And that this is an activity that’s lifelong, that’s holistic. Honestly, there’s been multiple times where I was just like, “maybe I’ll just go to school and do something different.” You know, like pursue a different career and move on. I don’t see any shame in that, and that’s a direction a lot of people go in. But every time I tried to leave this world behind, there was always something internal nagging at me to go back. Climbing is a part of who I am. And it makes me feel like the most whole and the best version of myself. And so being able to get that feeling back where I feel like pushing myself to my limits is fun—that’s just been really good for me. And I don’t think I can ever go back from that at this point.</p>
        </div>
    )
}
export default Kai_Lightner;