import React from "react";
import '../../css/dt.css';
import ReactPlayer from "react-player";
import img1 from '../../../img/News/Rare_Upgrade/1.webp';


const Rare_Upgrade =()=>{
    return(
        <div className="test">
            <h1>Jakob Schubert Offers a Rare Upgrade</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>Plus: Jesse Grupper flashes 5.14c; Kai Whaley skips two grades to climb V16; Katie Lamb knocks down two more V14s; and a podcast host finds his best bouldering form yet, thanks to not training.</p>
            <img className="img_bv" src={img1}></img>
            <p style={{fontStyle:'italic'}}>In an attempt to make space for the newsworthy ascents that occur with ever-increasing regularity, our weekly news series tries to celebrate a few outstanding climbs (or interesting events) that for one reason or another caught our attention. We hope you enjoy it. —The editors</p>
            <h2>Jesse Gruper Flashes Pure Imagination </h2>
            <p>A confession: I don’t really follow comps. Sure, I fast forward through the occasional World Cup replay, and I check the Team Trial results to see who’s on the international team this time around, but I wouldn’t do this consistently if it wasn’t part of my job, and I still don’t set aside time to watch any competitions live. So it’s no real surprise that I first heard of Jesse Grupper not when he won his first adult Lead Nationals in 2019 but when he flashed Livin’ Astro, a 5.14c in Rumney, New Hampshire, in November 2021. (Until then the hardest known flash in Rumney, which just so happens to be my childhood crag, was 5.13d.)</p>
            <p>Astonished, I called Grupper, and in our subsequent interview I was surprised to learn two things. First, he had a full-time job at a biodesign lab at Harvard where he helped build mechanical exoskeletons that help stroke victims regain mobility. And second, he didn’t think he wanted to focus his life around climbing professionally. “Traveling full-time for climbing was super fun, and a real privilege,” he said of his then-brief stint on the World Cup circuit, “but I did miss getting to create stuff that would benefit humanity. That’s a constant struggle with climbing for me—how much good is it doing for others versus just for myself.”</p>
            <p>Two days later, however, he won Lead Nationals, and in March 2022 he secured himself a spot on the National Team, giving himself the chance—which he took—of going full-time as a climber again. Since then, it’s been hard even for me to overlook Grupper’s accomplishments. In 2022, he won two World Cups, podiumed in two more, and came close to taking the overall Lead Champion title. This year, he came in second at Koper and won the Pan American Games, securing himself a 2024 Olympic spot. And last week, on a break from his comp training, he went to the Red River Gorge and reiterated his outdoor flashing prowess, this time by getting the third flash (after Adam Ondra and Daniel Woods) of Jonathan Siegrist’s classic Pure Imagination (5.14c).</p>
            <p>“I’ve wanted this one for a while,” he wrote on his Instagram. “I first peeked at it while trying Golden Ticket four years ago and since then I’ve brewed the idea of giving it a good first go.”</p>
            <p>He prepared for it by watching several videos—and by making sure Alex Megos was there to call beta at him.</p>
            <p>“Getting through the initial crux, I felt a sense of relief. I wasn’t crazy for having this dream—regardless of what happened next. Finishing the last redpoint crux and eyeing up the finishing moves, I felt proud no matter how it ended. But dang it felt good to grab that jug.”</p>
            <p>Check out my <a href="https://www.instagram.com/p/C0SOHJ1O1Ad/?utm_source=ig_embed&ig_rid=c157c6a0-da30-47e7-9b7b-3df764c7376a">feature interview </a> with Grupper from 2022.</p>
            <h2>Jakob Schubert upgrades an Alex Megos 5.15</h2>
            <p>Speaking of Alex Megos: One of his 5.15a’s just got upgraded to 5.15b by one of the world’s most prolific downgraders.</p>
            <p>Megos established Clash of the Titans relatively quickly in 2017, but it went six years without a repeat, despite the fact that Jakob Schubert, who lives nearby and eats 5.15 for breakfast, has spent a lot of time trying it. This is saying something, since Schubert, who earlier this year became the third person in the world to climb a proposed 5.15d, has a reputation for climbing hard things very fast. During a nine-day trip to Siurana in December 2021, for instance, he sent Will Bosi’s King Capella, which he downgraded from 5.15c to 5.15b; La Capella, which he did fifth try and downgraded from 5.15b to 5.15a; La Furia de Jabali, which he did third try and downgraded from 5.15b to 5.15a; Jungle Speed (5.14c/d), which he flashed; and Last Night (5.14c/d).</p>
            <p>Schubert takes grades quite seriously. “I feel it’s the responsibility of everyone who is capable of climbing the hardest grades to also give their honest opinion,” Schubert says in his video about Clash of the Titans. “That’s why I’ve downgraded some routes in the past.”</p>
            <p>But with Clash of the Titans it was the opposite. “I’ve climbed quite a few 9a+’s and 9b’s,” Schubert says, “but none of them took as much effort as this route.” He tried it season after season, unable to link the crux sequence from the ground. But then—after finding some microbeta—he surprised himself by sending on just his second day on the route in the fall of 2022. This confused him, and made him hesitant to upgrade the route outright. “After all, the route doesn’t fit my preferred style, which is crimping, but there are quite a few open handholds on this route that gave me a hard time.” So he sought a third opinion, inviting Stefano Ghisolfi to try the climb and give his own perspective on the grade. The result of this is both a cool video and… an upgrade.</p>
            <ReactPlayer url='https://youtu.be/ukm8wVEAs5o' width="500px" playing={false} controls={true}></ReactPlayer>
            <h2>Katie Lamb does yet another V14</h2>
            <p>Katie Lamb just released <a href="https://www.instagram.com/ktlambies/?utm_source=ig_embed&ig_rid=4f0685da-4c22-44e6-a652-2f0bf7f401d3">a little Instagram</a> banger showing cut-up footage of her climbing two V14s: Deadlift, in Squamish, British Columbia, which she climbed in September, and Decided, in Mizugaki, Japan, which she sent on October 25. Lamb’s been on a serious spree this year, getting the fourth ascent of Box Therapy (V15 or V16), and the first female ascent of Spectre, which is V13 or V14 depending on your size.</p>
            <h2>Sam Prior stops training and does his first V15</h2>
            <p>While it’s not “cutting edge” per se, one of my favorite news stories of the last few days is about how Sam Prior—a rather busy man who owns two independent gyms in the UK, co-hosts the Careless Talk Climbing Podcast with Aidan Roberts, and is a new father—sent his first V15, Serenata, at what I’m informed is one of the UK’s least photogenic crags. The interesting thing about this ascent (in my opinion) is that the key to Prior’s success has been… to train less.</p>
            <p>Speaking to UKClimbing, Prior describes how he had an “epiphany” last year and decided that he was simply done with “training,” which he defined as “[doing] things I don’t want to do in the name of improvement.” Fingerboarding? Nope. Conditioning? Not that either. (Admittedly, he, like most stereotypical UK-crushers, loves board climbing, which some would consider a form of training.) The results, however, have been pretty impressive. With less time on his hands than ever before, he’s had his best year of climbing to date, knocking down numerous outdoor V13s and V14s, plus some mighty School Room testpieces and Serenata. Since the idea of renunciation and sacrifice is often baked into the popular understanding of athletic progress, it’s always fun for me to see people doing their best while also insisting on living fully and having fun.</p>
            <a href="https://www.instagram.com/reel/C0XGyVJNFD4/?utm_source=ig_embed&ig_rid=9e9d3975-1510-4bb9-a52f-a546708d1deb">This Instagram</a>
            <h2>Kai Whaley skips V14 and V15 with Sleepwalker</h2>
            <p><a href="https://www.instagram.com/kai_whaley_/?utm_source=ig_embed&ig_rid=e6ee4994-682f-4fcc-922c-d3465adf84d8">Kai Whaley</a>, a 17-year-old Las Vegas local and lifelong climber, has skipped V14 and V15 and made the 11th ascent of Sleepwalker (V16) at Red Rock. Two months ago, Zander Waller did the climb with a new beta (apparently available only to tall people) that he says makes the climb more like low-end V15. But Whaley seems to think V16 could be accurate, at least for him. Speaking to 8a.nu, he said, “I did make quite the big grade jump this season but that’s mainly because I decided to focus all my time on Sleepwalker after a few promising sessions. I have also gotten close on other hard climbs that will fill in the grade gap. It was a big physical and mental battle for me after some regression in the middle sessions… but in the end it was all worth it because I was able to do one of the most iconic climbs where I grew up.”</p>
            <h2>Watch Pete Whittaker do the 3rd Ascent of Stranger than Fiction</h2>
            <p>Last week my colleague Anthony Walsh wrote about Pete Whittaker making the third ascent (and first two-shoed ascent) of Mason Earle’s Moab testpiece Stranger of Fiction, which he thought was hard 5.14b. (Earle had originally suggested 5.14-.) Now you can watch the video:</p>
            <ReactPlayer url='https://youtu.be/wGQfQpjpq8I' width="500px" playing={false} controls={true}></ReactPlayer>
            
        </div>

    )
}
export default Rare_Upgrade;