import React from "react";
import '../../../css/dt.css';

import img1 from '../../../../img/knowledge/nutrition/Vegan/1.webp';
import img2 from '../../../../img/knowledge/nutrition/Vegan/2.webp';
import img3 from '../../../../img/knowledge/nutrition/Vegan/3.webp';
import img4 from '../../../../img/knowledge/nutrition/Vegan/4.webp';
import img5 from '../../../../img/knowledge/nutrition/Vegan/5.webp';

const Vegan =()=>{
    return(
        <div className="test">
            <h1>Can Going Vegan Help You Climb Harder?</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>The benefits to giving up meat and dairy are wide ranging, but is the life-change suitable for you?</p>
            <img className="img_bv" src={img1}></img>
            <p>A few years ago, if I had heard about Frank Metivier, I would have laughed.</p>
            <p>Metivier is in his late 40s, he’s slim and lean. He has shaggy, long straw-colored hair, a narrow face and blue eyes. Metivier spends his time traveling, climbing and surfing. He does handstands, posts pictures of food on Facebook and he loves animals. More than anything else, Metivier has one important and defining quality: his mission to spread the word about veganism. Originally from Quebec, Metivier travels across Canada and the U.S. to publicize his plant-based message. Neatly lettered across the side of his van are bold words, “Vigorous Vegan Vagabond.” He protests in supermarkets, shows videos in streets and hands out informational cards at crags.</p>
            <p>His devotion just seems a little…extreme. “Veganism” is one of those words that feels dirty. It’s strongly associated with people like Metivier, people that show footage of animal slaughters and call meat-eaters murderers or animal rapists. It’s a word that evokes a slew of negative emotions—apprehension, irritation and shock. Vegan militants can feel preachy and unsympathetic to different perspectives. Food is, after all, cultural.</p>
            <p>I was the opposite of Metivier. I grew up in Dallas, Texas, the land of cattle ranches and barbeques. My parents would take me on three hour road trips with the singular purpose of purchasing fresh meats and cheeses. We ate eggs for breakfast, ham sandwiches for lunch, and meatloaf for dinner, just like everyone else in the area.</p>
            <p>Food really wasn’t something I thought about until I was twelve, the year I began climbing. When I qualified for the USA Team just seven months after joining the local youth team, my passion for the sport became an obsession. I spent more time training, worrying about upcoming competitions, and contemplating how I could give myself that extra edge. Nutrition has been an earmarked subject for me ever since.</p>
            <p>A few years ago, I heard some of my friends speaking about the various benefits of the vegan diet. For years, I had been eating the classic “athletes” diet: lean meats, low-fat dairy, nuts, seeds, colorful veggies, fruits, and so on. It was all… just fine. Mostly, I felt my body was getting old, somewhat inflamed, and I was questioning whether my habits were really helping me on my path. The more I listened to my friends, the more I began to wonder if I was missing out. I decided to give veganism a try for a few months, just as an experiment. My boyfriend at the time helped me craft vegan meals and showed me meat-replacing products to curb cravings.</p>
            <p>Strangely, after a few months, I felt stronger while climbing, and I noticed I was recovering faster. It’s been nearly three year since, and I’ve never looked back.</p>
            <p>Sound too good be to true? I agree. The scientist in me, the part that earned a degree concentrated in Sports Medicine from CSU, had me doing the research to quantify what may or may not be the placebo effect. Is veganism actually good for you, or are the health benefits just propaganda from animal-rights activists like Metivier? Are there any risks of nutritional deficiencies? And of course, does it actually help sports performance? Here’s what I found.</p>
            <h4 style={{fontStyle:'italic'}}>This article is free. Please support us with a membership and you’ll receive Climbing in print, plus our annual special edition of Ascent and unlimited online access to thousands of ad-free stories.</h4>
            <h2>Is it Feasible?</h2>
            <p>One of the biggest problems with going vegan is that the diet is fundamentally exclusionary. No animal products means no family brisket, no (regular) mac-n-cheese, no Friday night Kung-pow chicken take-out. While it’s true that Miguel’s offers vegan options, there’s no getting around the fact that your usual order will taste different.</p>
            <div style={{display:'flex'}}> 
                <div>
                    <p>According to Oceana McKenzie, Australia’s young rising star and finalist at the 2019 Moscow Bouldering World Cup, “[Being vegan] is quite natural and so I don’t think a lot about it as it is just what I do. I really enjoy vegan foods and I found that there are actually a lot more options when eating vegan.” What Mckenzie means by “more options” is that when your diet revolves around meat, you tend to eat the same meals over and over again (or, at least I did before making the switch). You meals don’t actually have revolve around some sort of meat-based main course. Putting it another way: plants are more versatile.</p>
                    <p>Plus, grabbing a vegan snack can actually be as easy as you want it to be. Fast food restaurants like Burger King, Carl’s Jr, Subway, Chipotle and Taco Bell all provide veggie patties or soy-based “meat.” And you can, in fact, find vegan versions of man-n-cheese at any grocery story.</p>
                </div>
                <div>
                    <img className="img_bv" src={img2}></img>
                </div>
            </div>
            <p>Personally, after a month or two of making the switch, I didn’t think it was hard. I love salads, and I love ordering a large vegan pizza after a long day. Of course, everyone is different.</p>
            <p>Preferences aside, there is one thing that logistically requires concern—Vitamin B12. Vitamin B12 is produced by bacteria found in soil. If we didn’t clean our produce, vegans wouldn’t need to be concerned about this one at all, they’d just get sufficient amounts while eating fresh plants. Meat eaters don’t have to worry because the meat they consume contains the B12-synthesizing bacteria.</p>
            <p>If B12 stores get low, anemia or nervous system damage can result. The U.S. recommended dietary allowance for B12 is 2.4 micrograms (mcg) a day. Other studies say even more is necessary, and since there are no side effects from overdosing, it’s better to err on the side of caution. According to Rami Najjar, a PhD student at Georgia State University, vegans should supplement 2,500- 5,000 mcg per week or 250-500 mcg per day of B12 in order to absorb sufficient amounts.</p>
            <h2>Is it actually good for people?</h2>
            <p>How does veganism affect our biggest health problems, especially the problems faced by athletes?</p>
            <h3>Cardiovascular disease</h3>
            <p>Cardiovascular disease (CVD) is the leading cause of death in the United States.  According to the Center for Disease Control and Prevention, CVD accounts for one out of every four deaths per year. Even among athletes, CVD is a risk that shouldn’t be overlooked.</p>
            <p>“We all know exercise is good for us,” said Barbara Morrison, a PhD student at the University of British Columbia. “However, even if you are really active, our findings suggest that you still can’t outrun your risk factors,” she continued. In Morrison’s study, which was published in <a href="https://bmjopensem.bmj.com/content/4/1/e000370">BMJ Open Sport and Exercise Medicine</a>, 11% of the 798 athletes over 35 were found to have significant CVD. 10% didn’t have any symptoms.</p>
            <p>So how do we mitigate our risks? Exercise is only part of the equation. The easiest culprit to attack is our diet. CVD is caused by atherosclerosis, which is the buildup of fat, cholesterol, and other substances along arterial walls. This buildup prevents blood flow and causes inflammation. According to a study published in the International Journal of Preventative Medicine, “the oxidation of low density lipoprotein (LDL) indicates the first step of atherosclerosis in CVD.”</p>
            <p>In a review paper by James H O’Keefe Jr published in the Journal of the American College of Cardiology, multiple studies have actually demonstrated that “the physiologically normal LDL level and the thresholds for atherosclerosis development … are approximately 50 to 70 mg/dl.” “Normal” LDL levels in the USA are classified as being between 90 to 130 mg/dl, which is nearly twice the reported physiological level.</p>
            <p>Because a plant-based diet contains no LDL, it is the only diet ever shown to reverse CVD. In a 2014 study, 198 patients were instructed to eat a diet of whole grains, beans, vegetables and fruits. Dairy, Fish, meat and oil were eliminated from participants’ diets. Of the compliant participants, (89% of the total participants), 39 had total disease reversal while 105 had significant symptom reduction, including resolution of chest pain. The patients that chose not to comply had no disease improvements and two-thirds experienced disease progression.</p>
            <h3>Cancer</h3>
            <div style={{display:'flex'}}> 
                <div>
                    <p>Cancer is the second leading cause of death in the United States. According to the National Cancer Institute, approximately 38.4% of people will be diagnosed with cancer during their lifetime. As with CVD, a plant-based diet is the only diet that has ever shown to reverse cancer.</p>
                    <p>In a 2005 study, 93 volunteers with prostate cancer were randomly assigned to an experimental group, which consumed a plant-based diet, or to a control group, which consumed an omnivore diet. All volunteers had chosen not to undergo any conventional treatment, including radiation, surgery or therapy. Prostate specific antigen (PSA), a bio-indicator of prostate cancer, decreased 4% in the plant-based group and increased 6% in the control group. Notably, cancer-killing factors in the blood of the plant-based group was able to kill cancer cells nearly 8 times more than the control group.</p>
                </div>
                <div>
                    <img className="img_bv" src={img3}></img>
                    <h5 style={{fontStyle:'italic'}}>According to Dr. William C. Roberts, the Executive Director of Baylor Heart and Vascular Institute, Dean of Baylor University Medical Center, and Editor in Chief of both The American Journal of cardiology and Baylor University Medical Center Proceedings, “Atherosclerosis is easily produced experimentally in herbivores (monkeys, rabbits) by giving them diets containing large quantities of cholesterol (egg yolks) or saturated fat (animal fat). Indeed, atherosclerosis is one of the easiest diseases to produce experimentally, but the recipient must be an herbivore. It is not possible to produce atherosclerosis in carnivores (tigers, lions, dogs, etc.)… Although most humans consider themselves carnivores or at least omnivores, basically we humans have characteristics of herbivores.” Photo by Yuan Yue on Unsplash</h5>
                </div>
            </div>
            <p>The effects of a plant-based diet have not been tested on women with breast cancer, although there are currently ongoing studies. Based on the available research, the benefits of a plant-based diet are a promising cancer-cure for several reasons. The first reason concerns LDL levels. A 2014 study assessed 244 women with breast cancer and found that the patients with higher levels of serum LDL at diagnosis had larger and more aggressive tumors. Lower serum LDL means a lower risk of cancer. The second reason has to do with dietary fiber, which is an element only found in plants. A 2012 review paper involving 16 studies concluded that there is, “an inverse association between dietary fiber intake and breast cancer.” In a 2006 study, women eating a plant-based diet for two weeks had reduced estrogen as well IGF-1, which is strongly associated with all forms of cancer. Additionally, factors in their blood inhibited cancer cell growth and increased cancer cell death.</p>
            <div style={{display:'flex'}}> 
                <div>
                    <h5 style={{fontStyle:'italic'}}>IGF-1 is a growth hormone strongly associated with cancer. Because amino acid profile in meat closely resembles our own amino acid profile, the liver reacts adversely and produces more IGF-1. A 2011 study experimentally lowered IGF-1 levels in subjects via a plant-based diet. Prostate cell growth was consequently decreased and cancer cell death increased. When the participants returned to their omnivore diet, cancer cell growth/death returned to pre-intervention levels. Photo by Sebastian Holgado on Unsplash</h5>
                    <h3>Gut health:</h3>
                    <p>Scientists have recently nicknamed our gut as the “second brain.” On the surface, it seems our gut is merely in charge of digestion. However, this mass of nervous tissue contains over 100 million neurons and has been shown to affect our mental state, behavior and certain diseases. Depression and anxiety, some of the most common mental disorders in the U.S., have also been linked to the gut’s complex micro-biome. Scientists are only just beginning to understand the ways in which the gut influences the body, but it is clear that the relationship is significant to our health.</p>
                </div>
                <div>
                    <img className="img_bv" src={img4}></img>
                    <h5 style={{fontStyle:'italic'}}>IGF-1 is a growth hormone strongly associated with cancer. Because amino acid profile in meat closely resembles our own amino acid profile, the liver reacts adversely and produces more IGF-1. A 2011 study experimentally lowered IGF-1 levels in subjects via a plant-based diet. Prostate cell growth was consequently decreased and cancer cell death increased. When the participants returned to their omnivore diet, cancer cell growth/death returned to pre-intervention levels. Photo by Sebastian Holgado on Unsplash</h5>
                </div>
            </div>
            <div style={{display:'flex'}}> 
                <div>
                    <p>In a 2018 review paper on the effects of a vegan diet on gut microbiota, Ming-Wun Wong reported that vegan diets appear to not only alleviate metabolic syndrome but also diseases such as rheumatoid arthritis and possibly Parkinson’s. The study suggested that instead of pouring money into pharmaceuticals and treatments, our diet might hold the simplest, most applicable treatment to our biggest problems.</p>
                    <p>Trimethylamine-N-oxide (TMAO) is a byproduct of gut bacteria and a risk factor for heart disease. It arises from choline or carnitine, which are nutrients found in meat and eggs. The more animal products consumed, the higher the circulating TMAO levels. A study by Robert A. Koeth noted that those with the highest TMAO levels had almost three times the risk of getting heart disease. Additionally, Koeth noted that vegans, who won’t have TMAO in circulation, will in fact begin to produce TMAO after just three days of reintroducing meat into their diet.</p>
                </div>
                <div>
                    <img className="img_bv" src={img5}></img>
                    <h5 style={{fontStyle:'italic'}}>Eggs are high in protein and important vitamins and minerals. The list of institutions that regard eggs as a healthy part of a balanced diet is endless. It is worth noting, however, that not all research is so flattering. In a 2012 study that has since been widely cited, it was found that egg consumption accelerated atherosclerosis in a way similar to the effect of smoking. The study also noted that the harmful effects of eggs are not solely due to their high cholesterol content. Eggs lead to the production of TMAO, a harmful pro-atherosclerotic byproduct, they promote oxidized serum LDL and they promote endothelial dysfunction. Endothelial dysfunction occurs when the inner arterial lining fails to do its job, e.g. maintaining blood pressure, protect tissues from toxic substances, regulate blood clotting and control the substances that pass between blood and tissues.</h5>
                </div>
            </div>
            <h2>But Can it Help Sports Performance?</h2>
            <p>Ok, so a plant-based diet can, in fact, help us tackle common diseases. But how does it affect performance?</p>
            <p>When it comes to dietary changes, perhaps the biggest worry for athletes is how those changes will affect recovery. Without a solid recovery, performance is delayed and gains are minimized. It’s a concern for athletes at every level and every age.</p>
            <p>A plant-based diet reduces oxidative stress and inflammation and lowers cholesterol—all of which lead to better recovery. Inflammation in particular is often viewed as the root of all diseases and it may be why you’re feeling tired faster, not making it to finals in a competition, or not sending the proj before the end of your trip. It’s a big, big problem, and the plant-based diet alleviates it.</p>
            <p>While there isn’t any scientific literature that specifically looks at the health status of vegan climbers, there are several studies on endurance runners. A recent study, published in 2019, compared vegan endurance runners with their omnivore counterparts. The study concluded that “adhering to vegetarian kinds of diet, in particular to a vegan diet, is associated with a good health status and, thus, at least an equal alternative to an omnivorous diet for endurance runners.”</p>
            <p>A quick Google search will tell you that the list of prestigious, vegan athletes is long— including world heavyweight champion Mike Tyson, 16 ultramarathon winner Scott Jurek and seven-time Grand Slam winner Venus Williams. For climbers, the list is slowly growing. Ashima Shiraishi, who has won eight IFSC gold medals and climbed two V15s, might be the most familiar name on the list</p>
            <p>“I feel happier and stronger from the change,” said Shiraishi on Instagram.</p>
            <h2>Environmental Impact:</h2>
            <p>As climbers that live and play outside, it’s our responsibility to consider how our actions affect the world around us.</p>
            <p>According to the Food and Agriculture Organization of the United Nations (FAO), about 14.5 percent of global green house gas emissions can be attributed to livestock, which is approximately equivalent to the emissions burned by all transportation vehicles (cars, trucks, trains, planes, etc.). The FAO noted that worldwide efforts to reduce green house gas emissions will be required in order to avoid the devastating effects of a warmer world. Unfortunately, the United Nations Environment Programme (UNEP) shows that “country pledges to reduce green house gas emissions will deliver no more than one-third of what is needed by 2020 to avoid a 2 degree Celsius rise in global temperature.”</p>
            <p>According to a 2016 study published by the American Chemical Society, the average American diet produces 1,984 pounds of carbon dioxide annually. If beef is replaced with plants, that figure drops down to 73 pounds of carbon dioxide.</p>
            <p>The FAO also noted that animal agriculture is the leading cause of deforestation, water and air pollution and biodiversity loss. Almost a third of biodiversity loss can be directly attributed to animal agriculture.</p>
            <p>You don’t have to go fully vegan to reduce your footprint. “I travel so much that it’s easier to be a bit flexible and not stress my diet too much,” said Alex Honnold in an interview with Climbing, who is famously known for his free solo of El Capitan. “By eating plant based 95%+ of the time I’m still minimizing my impact without having to worry about rules too much.”</p>
            <p style={{fontStyle:'italic'}}><a href="https://www.instagram.com/plantbased_climber/?hl=en">Rami Najjar</a> was a huge help in doing the research for this article. Najjar is a Ph.D. student studying Chemistry with a concentration in Nutrition at Georgia State University. He has a Masters of Science in Nutrition. Najjar has published three studies regarding plant-based diets as a treatment in the clinical setting for hypertension, inflammation and heart failure. Najjar has presented research at the American Heart Association and at a variety of other conferences. In his current PhD program, Najjar is examining the biochemical and mechanistic underpinnings contributing to the success of a plant-based diet with a particular focus on inflammation and oxidative stress in cell and animal models.</p>
        </div>
    )
}
export default Vegan;