import React from "react";
import '../../../css/dt.css';

import img1 from '../../../../img/knowledge/nutrition/VitaminD/1.webp';
import img2 from '../../../../img/knowledge/nutrition/VitaminD/2.jpg';
import img3 from '../../../../img/knowledge/nutrition/VitaminD/3.jpg';
import img4 from '../../../../img/knowledge/nutrition/VitaminD/4.webp';


const VitaminD =()=>{
    return(
        <div className="test">
            <h1>Recover Faster And Feel Happier: Why You Should Probably Supplement Vitamin D</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>Studies indicate Vitamin D impacts recovery, mood, immunity, and more. And chances are, if you're like over half of Americans, you're deficient.</p>
            <img className="img_bv" src={img1}></img>
            <p>With flu levels high and COVID-19 still lingering, knowing how to support our immune systems and guard our bodies has never been more relevant. While providing direct immune system support, vitamin D is also an incredible nutrient that impacts mood as well as athletic recovery. For any active individual wanting to keep their bodies in primo sending-shape, making sure vitamin D serum levels are healthy is an absolute MUST.</p>
            <p>Known as the “sunshine vitamin,” vitamin D is unique in the nutrient world in that it is the only vitamin that we synthesize in our body as a result of sunlight exposure. Basically, when sunshine—more specifically UVB rays—hits the cholesterol in our skin, a chemically inactive form of Vitamin D is synthesized. The newly created vitamin D must then travel first to the liver, and then to the kidneys to be fully transformed into the biologically active vitamin D3. This incredible vitamin (which is actually a hormone) is integral in supporting bone mineral density, immune system function, brain health, cardiovascular integrity, a healthy mood, gene expression, and so much more.</p>
            <p>Although we can make it in our bodies, insufficient and deficient levels are alarmingly present. Recent data from the National Health and Nutrition Examination Survey found that of the 4, 495 people examined for vitamin D levels, 41% were deficient (defined as less than 20 ng/mL). And according to the Centers for Disease Control and Prevention and the U.S. Department of Agriculture, over half of all Americans do not have optimal vitamin D levels, regardless of age. How can this be, when sunlight is so accessible? Well, there are a lot of factors that impact vitamin D synthesis.</p>
            <p>Higher latitudes, use of sunscreen, older age, and darker skin tones are all factors that would decrease vitamin D absorption. During most winter months, UVB rays are blocked, so even if you spend time in the sun you will not produce any vitamin D. Also, if you carry excess body fat, the vitamin D you do make gets sequestered in fat cells and is not available for the body to use.</p>
            <p>Vitamin D receptors are found in every tissue and cell in the human body, and vitamin D also regulates over 1000 different genes (gene expression is the process in which information from a gene is transformed into biochemical the body needs to function and stay healthy). Vitamin D supports brain function and development, which impacts mood, memory, and cognition. Vitamin D also modulates the immune system—helping it to make sure that it does not overreact or underreact. Vitamin D plays an important role in maintaining gut integrity and intestinal homeostasis between the person and their gut microbiome. Vitamin D promotes mucosal barrier function which further contributes to a healthy microbiome and inflammation modulation within the gut.</p>
            <p>As miraculous as it might sound, the “sunshine vitamin” also supports: cardiovascular health, bone health, healthy blood sugar levels, healthy C-reactive protein levels, a balanced inflammatory response, muscle strength, balance, respiratory health, prostate health, breast health, joint function and mobility, healthy aging and more!</p>
            <p>Important to note: At low levels, vitamin D’s primary function in the body is to regulate calcium in the blood to balance the body’s pH. At low levels, vitamin D is not able to support the other systems in the body. This is why we need to make sure our tanks are FULL at all times.</p>
            <p>Vitamin D is not a miracle cure; however, it is necessary for the functioning of so many systems, organs, tissues, and genes that improving health becomes much more difficult if you are deficient in or have suboptimal levels of this important nutrient.</p>
            <h2>Focus on Immuni-D</h2>
            <img className="img_bv" src={img2}></img>
            <p>If you’re an active individual, serious athlete, or well, anyone for that matter, looking to optimize your immunity may be at the top of your list. The most recent research shows that when it comes to COVID-19, healthy blood serum levels of Vitamin D may be a matter of life and death. One study, in Indonesia, compared two groups of patients (those who died, and those who survived). There were 780 patients total diagnosed with SARS-CoV-2. It was found that nearly 90% of those patients who had insufficient levels of Vitamin D died (levels {'<'}20 ng/mL), while only 4% of patients with normal levels of Vitamin D died (levels {'>'} 30 ng/mL). An increasing number of researchers and clinicians are suggesting that Vitamin D supplementation can potentially reduce the severity of COVID-19!</p>
            <h2>It’s all about your MooD</h2>
            <img className="img_bv" src={img3}></img>
            <p>Is there anyone out there who has ever experienced the “winter blues” or SAD (Seasonal Affective Disorder)? Well I sure have, especially when I lived on Vancouver Island during the winter months. It turns out that there are many components associated with sunshine that positively impacts our mood—the warmth on our skin, sun rays peeking through clouds, and yes, vitamin D production! Vitamin D receptors are found throughout the central nervous system, where vitamin D plays an integral role in neurotransmitter production—like the feel good chemical messengers dopamine and serotonin, for example. Studies show that low blood serum levels of vitamin D are associated with reduced cognitive function, anxiety, and depression. Research from a double-blind study done in Australia, showed that taking as little as 400IUs of vitamin D for only five days produced measurable improvements in mood!</p>
            <h2>Athletic Recovery, with vitamin D!</h2>
            <p>Just about every competing athlete has experienced that time when they trained really hard for an event, and then their bodies were bombarded with cold-like symptoms. Sound familiar? Well, believe it or not—as wonderful as exercise is—over-exertion and training add compounding stress on our bodies that can actually impact our immune system function. As discussed above, vitamin D is an impressive tool that can keep our immune systems in tip-top shape during training and leading up to an event, but it also has a unique ability to help our bodies modulate pain—yes, PAIN.</p>
            <p>Vitamin D is beginning to be understood as a hormone associated with chronic pain when at low levels, and connected to pain relief when those levels are increased. Current research shows that those who suffer from musculoskeletal pain, headaches, menstrual pain, fibromyalgia, and even pain accompanying sickle cell anemia have low levels of vitamin D. Studies show that simply increasing those levels leads to pain relief. Other research indicates that 85% of vitamin D deficient patients responded favorably to supplementation of vitamin D with a significant decrease in pain.</p>
            <p>What does this mean for you as an athlete? It means that vitamin D levels support a healthy training program, allowing you to train harder, for longer, while supporting proper immune system function. This also means that vitamin D can help promote athletic recovery by supporting occasional aches and pains associated with an active lifestyle. I know that for me, keeping vitamin D on hand at home, in my office, and certainly taking it during those dark winter months will be a key for supporting my athletic success—no matter the season, no matter the activity!</p>
            <h2>Supplementing with vitamin D: What to Know </h2>
            <p>A few things to be aware of with vitamin D:</p>
            <ol className="ul-li">
                <li>As mentioned above, vitamin D3 is what our bodies make and is the most bioavailable form when taken supplementally.</li>
                <li>Vitamin D is a fat-soluble vitamin, which means that it needs fat to increase absorption and utilization.</li>
            </ol>
            <p>Therefore, naturally my favorite supplement products will be those in the D3 form and paired with a healthy fat!</p>
            <p>Here are a few of my favorite vitamin D products:</p>
            <ul className="ul-li">
                <li>Mykind Organics Vegan D3 Spray by Garden of Life: I absolutely love the convenience and taste of this spray, and for me, this is a must have for my office drawer of essentials. This product is sugar free and lightly sweetened with organic stevia. The D3 is paired with organic pumpkin seed oil and organic cranberry seed oil to help increase absorbability. 1 spray is 1000 IU’s, so it is easy to adjust the amount to what is right for you. Simply spray and you’re good to go!</li>
                <li>Ultimate Omega-D3 by Nordic Naturals: This 2-in-1 product is the perfect way to synergistically blend vitamin D3 with omega-3 essential fatty acids. This combination is a great way to further support heart health, cognitive function, healthy inflammation levels, and more!</li>
                <li>Vitamin D3 Body Cream by Life-Flo: If you’re anything like me, you DO NOT want to feel as if you are taking a bazillion supplements. So why not supplement with D3 every time you put on body lotion? That’s right, vitamin D3 body creams are a fast and effective way to support healthy vitamin D levels in the body. This is a convenient product to leave at your office, by your bedside table, or in your car for on the go!</li>
            </ul>
            <p>In terms of specific dosing for your body, most vitamin D researchers agree that optimal levels of vitamin D are between 30 to 65 ng/ml of 25- hydroxy-vitamin D. It is important to get your vitamin D blood serum levels tested through your primary physician or local Naturopathic Doctor. From there, they can help you assess the right dosing recommendations for you.  Some researchers suggest that 5000 IUs daily is a good starting point for most athletes. Keep in mind that the most bioavailable forms are paired with a healthy fat, therefore the liquid sublingual forms will be the most rapidly absorbed and readily utilized.</p>
            <p>Whether you are an avid athlete training for a specific event, an active individual, or weekend warrior, making sure you are getting enough vitamin D3 through diet, lifestyle, and supplements is a great way to support healthy immune system function, a positive mood, and promote healthy recovery.</p>
            <div style={{display:'flex'}}> 
                <div>
                    <p style={{fontStyle:'italic'}}>Emily Ipsen, CHN, CNTP, MNT, NHC, is a certified nutrition therapy practitioner with a Master in nutrition therapy from the Nutrition Therapy Institute of Denver. Ipsen currently practices as a nutrition health coach at Natural Grocers. </p>
                </div>
                <div>
                <img style={{width:'300px'}} className="img_bv" src={img4}></img>
                </div>
            </div>
        </div>
    )
}
export default VitaminD;