import React from "react";
import '../../../css/dt.css';

import img1 from '../../../../img/knowledge/trainning/Collagen_Protein/1.webp';
import img2 from '../../../../img/knowledge/trainning/Collagen_Protein/2.webp';

const Collagen_Protein =()=>{
    return(
        <div className="test">
            <h1>Is Collagen Protein Worth the Hype?</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>More climbers than ever are stirring collagen into their morning coffee, or snacking on gelatin, trying to keep their tendons healthy. But are these supplements actually helping?</p>
            <img className="img_bv" src={img1}></img>
            <p>Collagen protein is having a moment. The supplement, which is being hocked by seemingly any climber with a 20-percent-off discount code, is reported to have myriad benefits. Most notably for climbers, the supplement expedites our bodies’ collagen synthesis process, which improves our overall tendon and ligament health. But are these supplements actually effective? Research in this area is growing, and current results show some benefits with study limitations. But consuming collagen supplements is certainly not the only way to improve collagen synthesis in the body—and there are other important nutrients that we should not neglect.</p>
            <h2>Our Body and Collagen—and What’s at Stake</h2>
            <p>Our musculoskeletal tissues—such as tendons, ligaments, cartilage, and bone—are predominantly composed of collagen protein (~70%), making it the most abundant protein in the human body. Our tendons attach muscle to bone and rely on elasticity to absorb shock for muscle tissue. Our ligaments, on the other hand, attach bone to bone and rely on being stiff and strong. Exercise can increase collagen synthesis to create denser and stronger tissue to absorb higher loads. Because of the high stresses placed on the musculoskeletal tissues, injuries are especially common in taxing activities like rock climbing. To make matters more complicated, ligaments and tendons have notoriously poor circulation which means they take much longer to heal compared to muscle or bone injuries. Thus, there is great interest in nutrition interventions for these tissues.</p>
            <h2>Collagen Intake for Collagen Synthesis</h2>
            <p>There are relatively few studies that have explored the link between collagen protein intake and how it influences collagen synthesis in athletes. There are currently no studies that focus on climbers. One widely cited study by those in favor of collagen supplementation—though not without limitations given that the sample size was merely eight participants— found that ingesting 15 grams of collagen with vitamin C sixty minutes before jump-rope skipping improved collagen synthesis compared to the group who consumed five grams of collagen and a placebo, sugar, who saw no improvement.(1) The group who consumed 15 grams of collagen with vitamin C had over double the amino acid content in their blood compared to the placebo group. Another study, of 48 collegiate male athletes who dosed 20 grams of collagen with vitamin C before weight training, found that supplementation improved their “rate of force development” (a measure of explosive strength) in maximal-isometric squat performance while the placebo sugar group did not.(2) Some argue that due to collagen’s high content of the amino acids—glycine, proline, and hydroxyproline, the required amino acids for collagen synthesis—collagen may be more beneficial than other protein types for collagen synthesis. However, no research has compared collagen to other protein types when dosed pre-exercise. Two studies of casein (a milk protein) found that casein consumed after exercise did not improve collagen synthesis.(3,4)</p>
            <img className="img_bv" src={img2}></img>
            <p>A 2023 study of 45 male and female recreational athletes found that the ingestion of 30 grams of whey protein (a milk protein) versus 30 grams of collagen protein versus a non-caloric placebo taken after resistance training did not increase collagen protein synthesis rates during the early states of post-exercise recovery.(5) The whey protein, however, did increase muscle protein synthesis rates, which is already well established in scientific literature that whey protein is helpful for muscle anabolism. Another 2023 study of 39 recreationally active males found that consuming 15 grams of collagen protein daily during a lower body resistance training program (3x/week for 15 weeks) did not enhance collagen synthesis.(8) In that study, collagen was consumed immediately post-workout or mid-afternoon on non-weight training days. One key difference in this study compared to the aforementioned studies is the direct measurements of collagen synthesis were taken by evaluating the size and mechanical properties of tendon tissue.</p>
            <p>While there is certainly more data needed in this area of research, these studies indicate that collagen may be most beneficial when taken 45-60 minutes pre-exercise as this may help transport the necessary amino acids to the target tissues: the tendons and ligaments. Inquiring minds, myself included, would like to know: can we take other types of protein pre-workout and improve collagen synthesis in the tendons/ligaments? Or is collagen’s amino acid profile uniquely qualified to do the job? Studies comparing collagen to other proteins for collagen synthesis when taken pre-exercise would be helpful in determining unique benefits of collagen intake for collagen synthesis.</p>
            <p>While the above studies have focused on collagen’s potential for building connective tissue, it should be noted that collagen’s amino acid profile is not ideal for muscle protein synthesis, so it should not be the primary dietary-protein source.</p>
            <h2>How Diet Supports Collagen Synthesis</h2>
            <p>The most important factor in supporting appropriate collagen synthesis is eating enough food! Consuming adequate protein intake is also important: most climbers need anywhere from 1.2-2.2 g/kg of body mass of protein per day. Our bodies make collagen without direct collagen intake. That’s because we are getting the amino acids required for formation from a variety of animal and/or plant-based sources, and we can synthesize certain amino acids from others. Whether you’re omnivorous, vegetarian, or vegan, eat a variety of protein sources for a variety of amino acids (essentially the building blocks of protein). Certain micronutrients are also essential for collagen synthesis. While vitamin C gets all the hype, zinc, magnesium, iron, and copper are also required.(6,7) So, including fruits, vegetables, beans, and nuts/seeds daily will ensure consumption of a variety of micronutrients. It’s also important to note that if your collagen supplement contains vitamin C, do not consume collagen with your coffee because the heat will degrade the vitamin.</p>
            <p>So, what’s the verdict? Collagen protein supplementation may be beneficial to take 60 minutes before exercise or rehab, and unlikely to be beneficial outside that time window. But you absolutely don’t need to take a collagen supplement to support optimal collagen synthesis in the body—your overall diet is far more important.</p>
            <p style={{fontStyle:'italic'}}>Hayden James is a board-certified sports dietitian and dedicated sport climber.</p>
            <h2>Sources</h2>
            <ol className="ul-li">
                <li>Shaw, G., Lee-Barthel, A., Ross, M. L., Wang, B., & Baar, K. (2017). Vitamin C–enriched gelatin supplementation before intermittent activity augments collagen synthesis. The American Journal of Clinical Nutrition, 105(1), 136–143. </li>
                <li>Lis, D. M., Jordan, M., Lipuma, T., Smith, T., Schaal, K., & Baar, K. (2022). Collagen and vitamin C supplementation increases lower limb rate of force development. International Journal of Sport Nutrition and Exercise Metabolism, 32(2), 65–73. </li>
                <li>TROMMELEN, J., HOLWERDA, A. M., SENDEN, J. M., GOESSENS, J. P., VAN KRANENBURG, J., GIJSEN, A. P., VERDIJK, L. B., & VAN LOON, L. J. (2020). Casein ingestion does not increase muscle connective tissue protein synthesis rates. Medicine &amp; Science in Sports &amp; Exercise, 52(9), 1983–1991. </li>
                <li>Moore, D. R., Phillips, S. M., Babraj, J. A., Smith, K., & Rennie, M. J. (2005). Myofibrillar and collagen protein synthesis in human skeletal muscle in young men after maximal shortening and lengthening contractions. American Journal of Physiology-Endocrinology and Metabolism, 288(6).</li>
                <li>Aussieker, T., Hilkens, L., Holwerda, A. M., Fuchs, C. J., Houben, L. H. P., Senden, J. M., van Dijk, J.-W., Snijders, T., & van Loon, L. J. C. (2023). Collagen protein ingestion during recovery from exercise does not increase muscle connective protein synthesis rates. Medicine &amp; Science in Sports &amp; Exercise, Publish Ahead of Print.</li>
                <li>Li, J., & Kirsner, R. S. (2005). Wound Healing. In Surgery of the skin: Procedural dermatology. essay, Elsevier Mosby. </li>
                <li>Wu M, Cronin K, Crane JS. Biochemistry, Collagen Synthesis. In: StatPearls. StatPearls Publishing, Treasure Island (FL); 2022. PMID: 29939531.</li>
                <li>Balshaw, T. G., Funnell, M. P., McDermott, E., Maden-Wilkinson, T. M., Massey, G. J., Abela, S., Quteishat, B., Edsey, M., James, L. J., & Folland, J. P. (2023). The effect of specific bioactive collagen peptides on tendon remodelling during 15 weeks of lower body resistance training. Medicine &amp; Science in Sports &amp; Exercise.</li>
            </ol>
        </div>
    )
}
export default Collagen_Protein;