import React from "react";
import '../../../css/dt.css';

import img1 from '../../../../img/knowledge/trainning/Improve_Climbing/1.webp';
import img2 from '../../../../img/knowledge/trainning/Improve_Climbing/2.jpg';
import img3 from '../../../../img/knowledge/trainning/Improve_Climbing/3.jpg';

const Improve_Climbing =()=>{
    return(
        <div className="test">
            <h1>Jonathan Siegrist: Easy Sends Don’t Improve Your Climbing</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>How Jonathan Siegrist, possibly the most prolific sport climber in the United States, trained his anti-style and went from a vertical crimp specialist to a steep cave crusher.</p>
            <img className="img_bv" src={img1}></img>
            <h2>1. We Are Biased Toward Comfort</h2>
            <p>We all have a certain style of climbing that we gravitate toward. Most often this is simply because it’s the style we’re best at. However, I’ve learned through the years that it’s not the easy (or comfortable) sends that make us grow as climbers; it’s the anti-style, drawn-out, laborious ones that do. Switching up our focus can have a huge impact on how well we climb, and furthermore how much we enjoy climbing! I’ve experienced this myself more than once in my own climbing career.</p>
            <p>When I started climbing, I was drawn to technical, vertical routes with very bad holds and demanding footwork. As I progressed, though, I realized that if I wanted to keep testing myself and improving, I badly needed to learn how to climb overhanging routes as well. I used to fear climbing in caves until finally, after years of avoidance, I started to love them. As my skill pendulum swung toward steep climbing, I began to lose my tenacity for edges, tiny crimps ,and vertical routes. It’s a bizarre feeling to have your once-obvious strength transform into a weakness. So this autumn, I felt I needed to move back toward my roots and re-perfect my gnarly slab game. My first ascent in the Fins, Idaho, was just that—El Toro Resbaloso (5.14c) represented a trip back to how I first learned how to climb, and a style change my climbing desperately needed.</p>
            <img className="img_bv" src={img2}></img>
            <p>As I mentioned above, techy vertical routes were the types of climbs I was initially drawn to. I attribute this in large part to my formative years bouldering on Flagstaff Mountain above Boulder, Colorado, where even the “easiest” problems are characterized by razor-blade crimpers, tiny pebbles, and smeary feet. My crimp strength and ability to utilize my feet were generally pretty good. However, my proclivity for the vertical had made me intimidated by anything even remotely overhanging, and some grip positions, like pinching, felt almost impossible. And so I predominately concentrated on vertical projects, remaining downright afraid to climb in caves because I knew I would have to knock my level down by a few grades to have any chance of sending. Eventually, though, I realized that I would have to put my ego aside if I wanted to progress—after all, most of the hard routes around the world are steep. If I wanted to keep improving as a climber, I would have to get used to overhangs.</p>
            <p>The first thuggy route I really put everything into was Tommy Caldwell’s Front Range, Colorado, testpiece Vogue (5.14b) at the Industrial Wall south of Boulder. Given my progression and what I had accomplished already (circa 2008), this climb was an obvious next step. The steep, compression-style climbing felt so foreign and difficult. It took me months to adapt, and even when I finally succeeded, it was a struggle. I can remember screaming so hard on the send that my throat was hoarse the next day. I’d rarely had to manifest this sort of primal try-hard on a vertical edging route.</p>
            <h2>2. How to Improve Your Anti-style? Be Patient.</h2>
            <p>The process of becoming better at your anti-style is generally slow. For many years, I felt like I had a serious handicap when I climbed outside my comfort zone. The more time I spent on terrain I was uncomfortable with, the more my body adapted, though. I also found that my mental capabilities adapted as well—over time, I was more willing to go for it, in large part because as you get better at something it becomes way more fun!</p>
            <p>With this in mind, you need to be patient with yourself as you strive to improve at a “foreign” style. It may even take a year or two to really shift your climbing strengths. Realize that no matter who you are or how strong you are, you can’t be great at every style all at the same time. Climbing is a diverse sport, with many differing factors that can affect your ability. It therefore makes sense to lower your expectations when climbing outside your wheelhouse.</p>
            <p>I can personally speak to the utility of this approach—by lowering my expectations of what I “should” be capable of doing on overhanging rock, I was able to transform these types of climbs from a weakness into a strength. Ultimately, Jumbo Love (5.15b) was the culmination of my transition. This route is steep and generally very physical. The holds are not necessarily bad—they’re just far apart, and the movement is powerful and demanding. Not exactly what I would imagine being my best style, but after years of slowly shifting my preferences, something like Jumbo Love became possible.</p>
            <h2>3. When Your Anti-style Becomes Your Style: Return To Your Roots</h2>
            <p>Sadly, as I climbed more and more in caves and on Spanish-style resistance routes, I did lose my edge (no pun intended) on the vert. Despite this, I kept telling friends that vertical routes were my jam, but when I occasionally came back to them, I felt confused and out of place. This brings us back to El Toro Resbaloso, which was the exact dead-vertical style I desperately needed to revisit.</p>
            <img className="img_bv" src={img3}></img>
            <p>As I returned to the Fins in Idaho early this fall, I could feel how rusty my slab game was. If I wanted to have any chance at my vertical mega-project, I would need to get back on my feet (again, no pun intended). My good friend Tom Smart had bolted El Toro Resbaloso in 2015, and this season he handed the project off to me, as he was knee-deep in another. El Toro is a vert climber’s dream, one of those routes where if any one single hold were missing it would be unclimbable. The crux is cerebral and challenging in a way that you’d only encounter on bomber, dead-vertical limestone. It involves very high feet on tiny nubs or textured smears, impossibly small edges for just the tips of your fingers, and huge swaths of utterly blank wall in-between. It was not easy to return to this tenuous style, but I know deep down it was exactly what I needed! “Slab Jonathan” from 2008 would have been proud!</p>
            <p>There are myriad reasons why some styles simply feel better or worse for each of us. Some of these reasons are complex and deeply mental, while others are tied to our physical capabilities. For obvious reasons, the fingers can often be a weak link—on any style. If you feel like weak fingers are holding you back, then you are likely to make huge improvements if you train for finger strength. My course 6 Weeks to Stronger Fingers is a great option to lay the foundation in this area. At the end of the day, though, climbing on a wide variety of terrain is one of the best ways to improve your overall climbing ability. I can’t stress enough how important I think it is to embrace all kinds of rock types, climbing styles, and challenges! This is how we grow and improve as climbers.</p>
            
        </div>
    )
}
export default Improve_Climbing;