import React from "react";
import '../../../css/dt.css';

import img1 from '../../../../img/knowledge/trainning/Overgripping/1.webp';
import img2 from '../../../../img/knowledge/trainning/Overgripping/2.jpg';
import img3 from '../../../../img/knowledge/trainning/Overgripping/3.jpg';

const Overgripping =()=>{
    return(
        <div className="test">
            <h1>Stop Overgripping! Here’s How.</h1>
            <p style={{fontStyle:'italic', textAlign:'center'}}>Professional climber and coach Neil Gresham's advice for training yourself to grip holds just enough, and not so much you waste power.</p>
            <img className="img_bv" src={img1}></img>
            <p>How many times have you caught yourself clinging on twice as hard as necessary, as if trying to rip the holds off the wall? Over-gripping and excessive grip re-adjustment may be slightly different faults, yet they commonly occur in tandem and both can develop into nervous habits that can spiral out of control if left unchecked, with the obvious result that you waste power. In this article, we’ll look at how to diagnose if you have a significant fault in either of these areas, and review drills for overcoming the habit.</p>
            <h2>Gripping faults—the bigger picture</h2>
            <p>Before we dig into the specifics of gripping technique, the key is to take a look at the full chain of events leading to why you are over-gripping, and identify any potential underlying causal factors. Excessive grip-adjustment and over-gripping are most commonly caused by a fear of falling or a lack of confidence. These faults may also occur because you are less familiar with the holds on a particular type of rock, or perhaps feel that you’re lacking strength. A comprehensive fix requires a wholistic approach, so the first step is to take a deep breath and be honest with yourself. If you really hate falling onto bolts or reliable pro then this is exactly what you need to do. If you take practice falls (using safe belay practices and an experienced belayer) you’ll soon find that suddenly you aren’t gripping the holds as hard. Similarly, a bit of bouldering and hangboarding to top up your finger strength may have the effect of generally making you feel stronger and more confident. But note that this could also make things worse. This is a complex business and many over-powered boulderers struggle to grip holds with a relaxed style. The answer, if this applies to you, is to switch to climbing endurance circuits and longer routes and to focus on conserving grip strength using some of the tips that follow.</p>
            <img className="img_bv" src={img2}></img>
            <h2>Drills for preventing grip re-adjustment</h2>
            <p>Let’s look more specifically at how to diagnose and prevent excessive grip re-adjustment. First, the question is “how much readjustment is too much?” Coaches may disagree on this, but a loose a rule-of-thumb is that if you readjust your grip once every three or four moves then this is no big deal. However, if you readjust several times every move or up to every three moves then this could represent a recurring fault, which needs to be addressed. On the flip side, if you never re-adjust your grip then this signals that you are generally confident and adept at finding the best part of holds. However, it may be a bad sign and mean that you are blindly missing the best parts of holds or failing to spot those key moments when a quick re-adjustment would be hugely beneficial! Again, this is a complex business, so we have to have both scenarios in mind simultaneously when we perform drills.</p>
            <p>The main direct fix for over-gripping is simply to do drills where you drop the grade and spend time climbing well within your comfort zone, with this particular issue in the front of your mind. A great time to do this is during warm-ups where you only allow yourself one shot at gripping the hold. Resist the obvious temptation to rush straight to the hold and instead identify the best part of the hold by eye rather than feeling your way into it, especially when climbing on rock, as this will save time, energy and skin. It’s possible that you will improve at this naturally with experience; however, it’s equally likely that excessive grip re-adjustment will become more deeply engrained, so it really does make sense to work on it consciously.</p>
            <p>Reading the route or boulder problem from the floor is a valuable supportive tactical procedure to help reduce the amount of grip-faffing. Move around on the ground to change your perspective and view the holds from close in, far back and from both sides, as this may reveal crucial in-cut sections that you would otherwise have missed. By standing in close to the wall and looking up, you will see undercuts and may even spot holds that are hidden behind features. If you get the feeling that you gripped certain holds in the wrong place during an onsight, then check your work and re-examine the holds as you lower back down.</p>
            <h2>Drills for preventing over-gripping</h2>
            <p>You’ll know if you over-grip, and you don’t need me to tell you. Check yourself regularly to determine if you really do need to crush the holds. Over-gripping is unavoidable and expected in certain situations, like when you need to perform the crux or make absolutely sure that you don’t fall. Over-gripping can be classified as a minor fault that pops up perhaps slightly too often on moderately tough moves, when clipping or most likely, when running out the rope. However, in some cases over-gripping can be such a major recurring fault that it causes a debilitating perma-pump that triggers a wave on tension to run through the body. This in turn, can restrict technique and cause post-training tightness and soreness and so on. But don’t fret if you think you’re a major over-gripper. It can all be unravelled and corrected with the right approach.</p>
            <img className="img_bv" src={img3}></img>
            <p>First, over-gripping shares the same list of potential underlying causes that we examined for grip readjustment (fear of falling, lack of general confidence or strength etc). However, there’s another big one on the list—you don’t trust your feet. If this applies to you then page one is to do footwork drills on easier ground. There’s a lot to this and we’ll explore it in separate articles in this series. A good one to start with is  Use of the Toe.</p>
            <p>Having looked into other areas, if you still feel that you’re over-gripping then the obvious next stage is to do drills that address the gripping component. Again, drop the grade and remind yourself as you climb to use as little grip-strength as possible. Try to adopt a more passive gripping style. Use the open/drag grip and chisel grip as much as possible on edges rather than crimping excessively (see Techniques For Getting The Most Out of Holds). When using larger holds, drag your pads over the holds and rely more on friction. Remind yourself to breathe and relax. You won’t be able to do this when climbing at your limit unless you can do it well on easy terrain first. This is usually just a case of maintaining constant awareness and as soon as you make the effort you will see improvements.</p>
            <p>To reduce the likelihood that over-gripping is being caused by excessive muscle tension, stretch your forearms regularly but only after climbing and on rest days and never before or during climbing sessions. Tennis ball massage is a great supportive practice for reducing muscle tension in the forearms. Treat yourself after climbing or on rest days. A further preventative measure for over-gripping is to use a forearm extensor trainer regularly as in some cases the fault may be caused by an imbalance in strength between the flexors and the extensors. This will also help stave off injuries as part of the process.</p>
            <p>A final ploy to address over-gripping and excessive re-adjustment is to work a redpoint project as doing so will teach you to grip holds efficiently, whereas we are often prone to squandering grip-strength when onsighting.</p>
            <p>Neil Gresham has been working with the Climbing Team as a training author since 1999. He offers personalised training programs at <a href="https://www.neilgresham.com/">www.neilgresham.com</a></p>
        </div>
        
    )
}
export default Overgripping;