import img1 from "../../../img/location/Phanxipan/1.jpg";
import img2 from "../../../img/location/Phanxipan/2.jpg";
import img3 from "../../../img/location/Phanxipan/3.jpg";
import img4 from "../../../img/location/Phanxipan/2.webp";
import img5 from "../../../img/location/Phanxipan/4.jpg";
import img6 from "../../../img/location/Phanxipan/5.jpg";
function Phanxipan(){
    return(
        <div>
        <h1>Fansipan Mountain</h1>
        <h3>1. Geographical location</h3>
        <p>Fansipan (Vietnamese: Phan Xi Păng) is a mountain in Vietnam. The height of the mountain was 3,143 metres (10,312 ft) in 1909, but now the height of the mountain is 3,147.3 metres (10,326 ft). It is the highest mountain in the Indochinese Peninsula (comprising Vietnam, Laos, and Cambodia), hence its nickname "the Roof of Indochina". It is located in the Lào Cai Province of the Northwest region of Vietnam, nine kilometres (5+1⁄2 miles) southwest of Sa Pa in the Hoang Lien Son mountain range. Administratively, it is shared between Tam Đường district, Lai Châu and Sa Pa town, Lào Cai.</p>
        <img src={img1}></img>
        <span>The Fansipan Mount</span>
        <h3>2. Climbing</h3>
        <p>Fansipan can be climbed in a steep and fairly strenuous hike. Previously, it took about 5–6 days from Sa Pa to reach Fansipan peak and return. Now the total time is usually only about three days, even two days, or for experts and strong, healthy people, it can be done in one day.</p>
        <p>Tour companies in the area will arrange hikes to the summit taking from one to three days. Most recommend taking the two or three-day options, and few guides will take tourists on a round trip in a single day.</p>
        <p>A very small village is located at around 1,500 m (4,920 ft) where accommodation and food is offered. Further up, at 2,800 m (9,190 ft), is an overnight camp. Most booked trips include the use of these facilities in their price should they be required.</p>
        <img src={img2}></img>
        <span>The Roof of Indochina: it’s possible to climb Mt. Fansipan independently, without a guide, in one day</span>
        <h3>3. Guide: Climbing Mt. Fansipan</h3>
        <p>There are several trails to reach the summit of Mount Fansipan, known romantically as the ‘Roof of Indochina’. However, only one is easy enough (and safe enough) to follow independently, without a guide. This is the trail that begins at the entrance to Thác Tình Yêu (Love Waterfall), 15km west of Sapa on road QL4D. Known as the Tram Ton Pass trail, it’s fairly easy to follow and, despite local opinions to the contrary, can comfortably be climbed in one day, without a guide. However, it’s still essential to prepare and climb responsibly and safely. In this guide, I’ve tried to include as much information as I can so that other climbers who want to make the ascent independently may do so. However, please note that although all the information in this guide is accurate at the time of writing, I can’t guarantee that things won’t change in the near future.</p>
        <p>According to the signs at the trailhead, the one-way trek from the starting point of the Tram Ton Pass trail (at the entrance to Love Waterfall) to the summit of Mount Fansipan is 11.2km. We made the ascent in 6 to 6.5 hours. We climbed at a leisurely pace with regular short breaks, either to rest or to hydrate and have a snack, or to take photos and admire the views. We left our hotel in Sapa at a reasonable hour in the morning, after breakfast, sometime around 7.30am. The taxi ride to the trailhead takes 10-20 minutes, so we were on the trail by roughly 8.00am. We reached the summit after lunchtime, approximately 2.15pm. You could potentially make the ascent in under 6 hours if you’re very fit, don’t stop often, and have perfect trekking conditions. However, I would imagine that for most people of average fitness who simply want to successfully scale the highest mountain in Indochina and enjoy the walk, the views, and the experience (rather than treat it as an athletic contest), a general estimation would be anywhere from 6-9 hours. But there are other factors to consider: weather conditions might slow you down; perhaps you will get cramp and need an extended rest; maybe part of the trail is obstructed by a large branch or landslide. This is why you should leave fairly early in the morning, so that even if you encounter any unforeseen circumstances, you will still have time to reach the summit before nightfall. Note that, if you do run out of daylight hours, there are two permanent camps along the trail to the summit, one at 2,200m, the other at 2,800m.</p>
        <img src={img3}></img>
        <span>The hike on the Tram Ton Pass trail is 11.2km: it can be completed in one day if you start in the morning</span>
        <h3>4. Fitness & Endurance</h3>
        <p>Climbing Mount Fansipan in one day via the Tram Ton Pass trail is something that most people in reasonably good shape can do. However, it does require a significant physical effort and, because of the altitude, breathing difficulties caused by lack of oxygen make the climb even more of a challenge. When I made the ascent I was 34 years old and in pretty good physical condition. I was with my dad and uncle, who were 73 and 69 respectively, both of whom take daily exercise in the form of long-distance swimming and running. I found the ascent challenging but by no means exhausting. However, I do take regular, strenuous exercise. I also think that my concern for my dad and uncle’s physical well-being on the trek kept me focused on their efforts rather than my own. My dad and uncle both made the ascent without incident, but they both agreed it was one of the toughest physical pursuits they can remember undertaking. We encountered around a dozen other climbers on the trail (all with guides), most of whom were younger than us and had taken two days for the ascent, spending one night at one of the base camps. However, the other climbers appeared to be mostly of average fitness and had not had any trouble making the ascent. They seemed to be in good spirits and while they had found the climb challenging, they were not exhausted. The first half of the trail is well-marked and of moderate steepness, but the second half is rocky and very steep at times, involving metal ladder and peg-ladder climbs. Particularly grueling is the last couple of hours, when several steep ascents immediately descend again, which can be very demoralizing, especially as the air is getting thinner and your body more tired.</p>
        <img src={img4}></img>
        <span>Although strenuous, the climb can be completed by most people in reasonably good physical condition</span>
        <h3>5. Safety & Permission</h3>
        <p>Although Mount Fansipan can be climbed independently, without requiring any specialist equipment, climbing abilities, or permission, it is still vital that you treat the ascent seriously by preparing sensibly and climbing responsibly. There have been deaths on the mountain in recent years, including foreign tourists attempting the ascent without a guide. Like any high mountain, Fansipan can be dangerous, and the risks of climbing alone, without a guide, should not be underestimated.</p>
        <p>The trail is well-marked for most of the ascent and is fairly easy to follow. However, when the clouds descend on the mountain, visibility can be very bad, leading to difficulty finding your way. In damp conditions, the rocks can become very slippery. Tread carefully because even a minor slip can lead to an injury, and even something as small as a sprained ankle can cause big problems when on a cold, wet mountainside with no help. It should go without saying that straying from the trail, or climbing boulders and cliff faces without proper equipment, is an extremely bad idea.</p>
        <img src={img5}></img>
        <span>The dangers of climbing Mt. Fansipan, especially without a guide, should not be underestimated</span>
        <p>It’s essential to stay hydrated. Bring lots of water with you. The climb is strenuous so you will be perspiring all the time, even if it doesn’t feel like it because of the cool weather conditions. Dehydration leads to cramp, which can be a major hindrance, forcing you to stay static for hours at a time. Cramp may not sound serious, but if your legs cramp at 10,000ft as a storm is blowing in and the daylight is fading, your situation can suddenly become very grave. Make sure you bring some warm clothing. The mountain can get very cold, even in the summer months. If you get stuck on the mountain in freezing temperatures, hypothermia is a serious possibility.</p>
        <p>If possible, don’t climb alone. Go with a companion or a small group. If something happens to one of you, the other can get help. Bring your mobile phone. There’s a phone signal for most of the ascent. Make sure you have a local SIM card with plenty of credit. It’s best to get a Viettel SIM, because they tend to have the widest coverage in the mountains. Make sure your battery is fully charged, or even better, bring a USB battery pack so you can recharge your phone on the climb. Take a small flashlight in case it gets dark.</p>
        <p>When it comes to permission, before the ascent I’d read all sorts of stories about independent climbers not being allowed on the mountain, being turned back or even fined by national park authorities. In reality, however, we didn’t encounter any authorities on the climb, no tickets or permission papers were asked for, and none of the official guides we passed and spoke with mentioned anything at all about it. No doubt, one of the reasons the authorities and tourist agencies in Sapa say it’s not possible to climb Fansipan independently is because, if such a climber were to have an accident, it would not only be a personal tragedy, it would give the mountain and the national park bad press and a bad name. This seems reasonable to me. However, part of discouraging independent climbers is also likely to do with money. A guided climb can cost upwards of $100. And yet, we met a number of guides and their groups who didn’t appear to have safety in mind: they were climbing with flip-flops or, in some cases, with plastic bags over their shoes so as not to get them wet or dirty, thus increasing the chances of a nasty slip or fall because of the lack of traction. Unless things have changed by the time you read this, it certainly is possible to climb Fansipan independently, without a guide and without needing to get permission. However, if you do climb independently, have some respect for the mountain and for the independent climbers who will follow in your footsteps: don’t be reckless; climb responsibly and safely. If your negligence leads to an accident on the mountain, you give other independent climbers a bad name, and the authorities the perfect excuse to ban independent climbers in the future.</p>
        <img src={img6}></img>
        <span>On our climb, we weren’t asked for tickets or any kind of permission to scale the mountain independently</span>
        </div>
    );
}
export default Phanxipan;